export type Locale = 'en' | 'de';

const en = {
  'app.name': 'DHCPulse',
  'app.tagline': 'Local DHCP planning and analysis.',
  'nav.github': 'View source',
  'nav.language': 'Language',
  'shell.eyebrow': 'Private DHCP workbench',
  'shell.title': 'DHCPulse Workbench',
  'shell.description': 'Plan, build, analyze, troubleshoot, and secure DHCP changes. Your work stays in this browser and is never uploaded.',
  'shell.toolCount': '{count} tools ready',
  'catalog.search': 'Search tools',
  'catalog.searchPlaceholder': 'Search by task, topic, or protocol',
  'catalog.filters': 'Tool categories',
  'catalog.all': 'All tools',
  'catalog.group.plan': 'Plan',
  'catalog.group.build': 'Build',
  'catalog.group.analyze': 'Analyze',
  'catalog.group.troubleshoot': 'Troubleshoot',
  'catalog.group.secure': 'Secure',
  'catalog.empty': 'No matching tools found.',
  'catalog.emptyHint': 'Try another term or clear the search to see the complete workbench.',
  'catalog.clear': 'Clear search',
  'catalog.open': 'Open tool',
  'frame.back': 'Back to all tools',
  'frame.context': 'Source and context',
  'frame.contextDescription': 'Review the source guidance and adapt every result to your DHCP platform and operating environment.',
  'frame.resetUnavailable': 'No inputs to reset yet',
  'frame.resetTool': 'Reset tool',
  'frame.reference': 'Protocol reference',
  'notFound.title': 'Tool not found',
  'notFound.description': 'This workbench link does not match an available tool.',
  'panel.workspace': '{name} workspace',
  'panel.ready': 'This workspace is ready for local inputs and a reviewable result.',
  'hero.eyebrow': 'Local-first DHCP cutover planner',
  'hero.title': 'Plan the change. See when clients move.',
  'hero.description': 'Model lease timing, topology, relays, and rollback before a DHCP migration or option change. Nothing leaves your browser.',
  'hero.badge.local': '100% local',
  'hero.badge.noUpload': 'No uploads',
  'hero.badge.open': 'Open source',
  'form.title': 'Change scenario',
  'form.description': 'Use estimates. No production identifiers are needed.',
  'form.preset': 'Start with a real-world preset',
  'form.reset': 'Reset scenario',
  'section.change': '1. Change type',
  'section.timing': '2. Lease timing',
  'section.topology': '3. Topology',
  'section.clients': '4. Client profile',
  'scenario.migration': 'Server migration',
  'scenario.serverAddress': 'New DHCP server address',
  'scenario.leaseChange': 'Lease-duration change',
  'scenario.dnsChange': 'DNS option change',
  'scenario.emergency': 'Emergency replacement',
  'field.leaseDuration': 'Current lease duration',
  'field.newLeaseDuration': 'Target lease duration',
  'field.t1': 'T1 renewal',
  'field.t2': 'T2 rebinding',
  'field.clientCount': 'Estimated clients',
  'field.offline': 'Offline during cutover',
  'field.hours': 'hours',
  'field.percent': '%',
  'field.sameAddress': 'Will the DHCP service keep the same IP address?',
  'field.usesRelay': 'Do routed networks use a DHCP relay or IP helper?',
  'field.relayUpdated': 'Will every relay target the new service at cutover?',
  'field.leasesTransferred': 'Will the active lease database be transferred?',
  'field.samePool': 'Will old and new servers use the same address pool?',
  'field.bothActive': 'Will both DHCP servers answer during cutover?',
  'choice.yes': 'Yes',
  'choice.no': 'No',
  'help.timing': 'Defaults follow the common RFC 2131 values. Server and client implementations may use explicitly supplied values.',
  'help.leaseChange': 'A new duration applies to new or renewed leases, not leases already issued.',
  'validation.positive': 'Enter a value greater than zero.',
  'validation.percentage': 'Enter a percentage greater than 0 and below 100.',
  'validation.timingOrder': 'T1 must occur before T2.',
  'validation.nonNegative': 'Enter zero or a positive number.',
  'validation.range': 'Enter a percentage from 0 to 100.',
  'results.title': 'Cutover outlook',
  'results.invalid': 'Correct the highlighted timing values to calculate a plan.',
  'verdict.ready': 'Ready to plan',
  'verdict.caution': 'Proceed with caution',
  'verdict.noGo': 'No-go as entered',
  'summary.ready': 'No blocking condition is visible. Complete the checklist and validate with a representative client before approval.',
  'summary.caution': 'The change is feasible, but it depends on timing or operational controls shown below.',
  'summary.noGo': 'Resolve the blocking conditions before scheduling this change.',
  'metric.renewNow': 'Renewals expected in the first hour',
  'metric.rebindNow': 'Rebinding can begin after',
  'metric.oldLeasesGone': 'All old leases expire within',
  'timeline.title': 'Lease wave',
  'timeline.description': 'Estimated from a uniform spread of time until the next healthy T1 renewal.',
  'timeline.renewal': 'T1 renewal',
  'timeline.rebinding': 'T2 rebinding',
  'timeline.expiry': 'Lease expiry',
  'timeline.firstHour': 'About {count} clients reach this phase in the first hour',
  'timeline.startsAfter': 'The earliest clients reach this phase after {duration}',
  'timeline.allBy': 'Every current lease reaches it within {duration}',
  'findings.title': 'What changes the risk',
  'finding.livePoolOverlap': 'Both servers can answer from the same pool',
  'finding.livePoolOverlap.detail': 'Competing authoritative servers can allocate the same address. Stop one service or isolate its pool before cutover.',
  'finding.relayNotUpdated': 'A relay still targets the old service',
  'finding.relayNotUpdated.detail': 'Clients behind that relay may not reach the replacement server when they rebind.',
  'finding.leasesMissingForSharedPool': 'The shared pool has no transferred lease state',
  'finding.leasesMissingForSharedPool.detail': 'The new server cannot distinguish addresses still held by clients and may allocate a duplicate.',
  'finding.newServerAddress': 'Clients depend on rebinding to discover the new address',
  'finding.newServerAddress.detail': 'Initial unicast renewal can still target the old server until clients enter T2 or start a fresh DHCP exchange.',
  'finding.temporaryPoolCapacity': 'The separate replacement pool needs enough free capacity',
  'finding.temporaryPoolCapacity.detail': 'Collision risk is lower, but clients can consume the temporary pool while old leases remain valid.',
  'finding.offlineClients': 'Offline clients can return with old lease state',
  'finding.offlineClients.detail': 'Returning devices may request their previous address after the visible cutover wave.',
  'finding.leaseChangeNotRetroactive': 'Existing leases keep their original lifetime',
  'finding.leaseChangeNotRetroactive.detail': 'Only a successful renewal or new allocation receives the target duration.',
  'finding.optionChangeOnRenewal': 'Option changes arrive on renewal or a fresh lease',
  'finding.optionChangeOnRenewal.detail': 'Plan for the lease wave before expecting every client to use the new DNS option.',
  'finding.emergencyRecovery': 'Emergency replacement reduces preparation time',
  'finding.emergencyRecovery.detail': 'Preserve evidence and configuration state, then validate collision and relay risks before enabling service.',
  'finding.none': 'No additional timing risk detected for the entered topology.',
  'severity.blocker': 'Blocker',
  'severity.warning': 'Warning',
  'severity.info': 'Note',
  'checklist.title': 'Cutover checklist',
  'phase.prepare': 'Prepare',
  'phase.cutover': 'Cut over',
  'phase.validate': 'Validate',
  'phase.rollback': 'Rollback ready',
  'action.captureScopeOptions': 'Record scope, reservations, exclusions, options, and server-authorized state.',
  'action.backupConfiguration': 'Export and securely back up the current DHCP configuration.',
  'action.verifyTargetService': 'Validate target service time, authorization, bindings, firewall, and pool capacity.',
  'action.verifyLeaseTransfer': 'Compare transferred active leases and reservations before enabling the target.',
  'action.stageLeaseReduction': 'Stage the shorter lease early enough for current clients to renew before cutover.',
  'action.verifyRelayPath': 'Inventory every relay or IP helper and test the routed path to the target.',
  'action.freezeDhcpChanges': 'Freeze administrative DHCP changes and capture the final source state.',
  'action.stopOldService': 'Stop or isolate the old DHCP service before enabling an overlapping pool.',
  'action.startTargetService': 'Enable the target service and confirm it can offer from the intended scope.',
  'action.applyLeaseChange': 'Apply the target lease duration and confirm it is returned on a test renewal.',
  'action.applyOptionChange': 'Apply the planned DHCP option change to the intended scopes.',
  'action.applyRelayTarget': 'Apply and verify the planned relay or IP-helper targets.',
  'action.testRenewal': 'Renew a representative existing client and verify address, gateway, DNS, and lease lifetime.',
  'action.testNewClient': 'Test a new client with no existing lease state.',
  'action.monitorDhcpTraffic': 'Monitor DHCP discover, offer, request, acknowledgment, and negative acknowledgment events.',
  'action.verifyOptions': 'Verify effective DHCP options on at least one client per routed segment.',
  'action.defineRollbackTrigger': 'Define the exact failure threshold and decision owner for rollback.',
  'action.retainOldServiceState': 'Keep the previous configuration and lease state recoverable until the old lease window closes.',
  'action.retainPreviousConfiguration': 'Keep the previous option values and a tested reversal procedure available.',
  'rollback.title': 'Rollback window',
  'rollback.keepOldServiceRecoverable': 'Keep the old service recoverable but unable to answer until rollback is declared.',
  'rollback.restoreRelayTarget': 'Document the relay-target reversal and its validation command.',
  'rollback.restorePreviousConfiguration': 'Restore the captured option values and confirm the previous behavior on a test renewal.',
  'rollback.validateRollbackClients': 'After rollback, validate one renewing and one new client on each critical segment.',
  'assumptions.title': 'Model assumptions',
  'assumption.uniformRenewalSchedule': 'Before cutover, online clients are assumed healthy and evenly distributed across their T1 renewal cycle; clients already failing to renew are not modeled.',
  'assumption.clientBehaviorVaries': 'Client and server implementations may deviate from the default timing model.',
  'assumption.offlineEstimate': 'The offline-client percentage is an operator estimate.',
  'export.copy': 'Copy plan',
  'export.copied': 'Plan copied',
  'export.download': 'Download Markdown',
  'privacy.title': 'Your scenario stays here',
  'privacy.description': 'Processed only in this browser. No data is uploaded. DHCPulse has no backend, analytics, account, or storage feature.',
  'footer.disclaimer': 'Local workbench guidance, not a substitute for vendor documentation or tested operational controls.',
  'footer.rfc': 'Timing model: RFC 2131',
  'preset.safeMigration': 'Windows DHCP migration',
  'preset.safeMigration.detail': 'Same service address with transferred active leases.',
  'preset.newAddress': 'New server address + relay',
  'preset.newAddress.detail': 'Clients must discover a replacement at a new address.',
  'preset.dnsOption': 'DNS option rollout',
  'preset.dnsOption.detail': 'Estimate when option 6 reaches the client population.',
  'preset.collision': 'Unsafe overlap check',
  'preset.collision.detail': 'Expose duplicate-allocation risk before cutover.',
  'duration.minute': 'minute',
  'duration.minutes': 'minutes',
  'duration.hour': 'hour',
  'duration.hours': 'hours',
  'duration.day': 'day',
  'duration.days': 'days',
  'export.title': 'DHCPulse change plan',
  'export.scenario': 'Scenario',
  'export.assessment': 'Assessment',
  'export.timeline': 'Lease timeline',
  'export.findings': 'Risk findings',
  'export.checklist': 'Cutover checklist',
  'export.rollback': 'Rollback guidance',
  'export.assumptions': 'Assumptions',
  'export.currentLease': 'Current lease',
  'export.clients': 'Estimated clients',
  'export.generated': 'Generated locally with DHCPulse. Review and adapt this draft before use.',
} as const;

export type CopyKey = keyof typeof en;

const de: Record<CopyKey, string> = {
  ...en,
  'app.tagline': 'Lokale DHCP-Planung und -Analyse.',
  'nav.github': 'Quellcode ansehen', 'nav.language': 'Sprache',
  'shell.eyebrow': 'Private DHCP-Workbench', 'shell.title': 'DHCPulse Workbench',
  'shell.description': 'Plane, erstelle, analysiere, diagnostiziere und sichere DHCP-Änderungen. Deine Arbeit bleibt in diesem Browser und wird nie hochgeladen.',
  'shell.toolCount': '{count} Tools bereit',
  'catalog.search': 'Tools durchsuchen', 'catalog.searchPlaceholder': 'Nach Aufgabe, Thema oder Protokoll suchen', 'catalog.filters': 'Tool-Kategorien', 'catalog.all': 'Alle Tools',
  'catalog.group.plan': 'Planen', 'catalog.group.build': 'Erstellen', 'catalog.group.analyze': 'Analysieren', 'catalog.group.troubleshoot': 'Diagnose', 'catalog.group.secure': 'Absichern',
  'catalog.empty': 'Keine passenden Tools gefunden.', 'catalog.emptyHint': 'Versuche einen anderen Begriff oder lösche die Suche, um die gesamte Workbench zu sehen.', 'catalog.clear': 'Suche löschen', 'catalog.open': 'Tool öffnen',
  'frame.back': 'Zurück zu allen Tools', 'frame.context': 'Quellen und Kontext', 'frame.contextDescription': 'Prüfe die Quellenhinweise und passe jedes Ergebnis an deine DHCP-Plattform und Betriebsumgebung an.', 'frame.resetUnavailable': 'Noch keine Eingaben zum Zurücksetzen', 'frame.resetTool': 'Tool zurücksetzen', 'frame.reference': 'Protokollreferenz',
  'notFound.title': 'Tool nicht gefunden', 'notFound.description': 'Dieser Workbench-Link passt zu keinem verfügbaren Tool.',
  'panel.workspace': '{name}-Arbeitsbereich', 'panel.ready': 'Dieser Arbeitsbereich ist für lokale Eingaben und ein nachvollziehbares Ergebnis vorbereitet.',
  'hero.eyebrow': 'Lokaler DHCP-Cutover-Planer',
  'hero.title': 'Plane den Change. Sieh, wann Clients wechseln.',
  'hero.description': 'Modelliere Lease-Zeiten, Topologie, Relays und Rollback vor einer DHCP-Migration oder Optionsänderung. Nichts verlässt deinen Browser.',
  'hero.badge.local': '100 % lokal', 'hero.badge.noUpload': 'Keine Uploads', 'hero.badge.open': 'Open Source',
  'form.title': 'Change-Szenario', 'form.description': 'Schätzwerte reichen aus. Produktivdaten werden nicht benötigt.',
  'form.preset': 'Mit einer Praxisvorlage starten', 'form.reset': 'Szenario zurücksetzen',
  'section.change': '1. Art des Changes', 'section.timing': '2. Lease-Zeiten', 'section.topology': '3. Topologie', 'section.clients': '4. Client-Profil',
  'scenario.migration': 'Servermigration', 'scenario.serverAddress': 'Neue DHCP-Serveradresse', 'scenario.leaseChange': 'Lease-Dauer ändern', 'scenario.dnsChange': 'DNS-Option ändern', 'scenario.emergency': 'Notfallersatz',
  'field.leaseDuration': 'Aktuelle Lease-Dauer', 'field.newLeaseDuration': 'Ziel-Lease-Dauer', 'field.t1': 'T1 Renewal', 'field.t2': 'T2 Rebinding', 'field.clientCount': 'Geschätzte Clients', 'field.offline': 'Beim Cutover offline', 'field.hours': 'Stunden', 'field.percent': '%',
  'field.sameAddress': 'Behält der DHCP-Dienst dieselbe IP-Adresse?', 'field.usesRelay': 'Nutzen geroutete Netze ein DHCP-Relay oder einen IP-Helper?', 'field.relayUpdated': 'Zeigen alle Relays beim Cutover auf den neuen Dienst?', 'field.leasesTransferred': 'Wird die aktive Lease-Datenbank übertragen?', 'field.samePool': 'Nutzen alter und neuer Server denselben Adresspool?', 'field.bothActive': 'Antworten beide DHCP-Server während des Cutovers?',
  'choice.yes': 'Ja', 'choice.no': 'Nein',
  'help.timing': 'Die Vorgaben entsprechen den üblichen RFC-2131-Werten. Server oder Clients können explizit übermittelte Werte verwenden.', 'help.leaseChange': 'Eine neue Dauer gilt für neue oder erneuerte Leases, nicht rückwirkend.',
  'validation.positive': 'Gib einen Wert größer als null ein.', 'validation.percentage': 'Gib einen Wert größer als 0 und kleiner als 100 ein.', 'validation.timingOrder': 'T1 muss vor T2 liegen.', 'validation.nonNegative': 'Gib null oder eine positive Zahl ein.', 'validation.range': 'Gib einen Prozentwert von 0 bis 100 ein.',
  'results.title': 'Cutover-Ausblick', 'results.invalid': 'Korrigiere die markierten Zeitwerte, um den Plan zu berechnen.',
  'verdict.ready': 'Planungsbereit', 'verdict.caution': 'Mit Vorsicht fortfahren', 'verdict.noGo': 'So nicht freigeben',
  'summary.ready': 'Keine blockierende Bedingung erkennbar. Arbeite die Checkliste ab und teste einen repräsentativen Client vor der Freigabe.', 'summary.caution': 'Der Change ist machbar, hängt aber von den unten gezeigten Zeiten oder Betriebsmaßnahmen ab.', 'summary.noGo': 'Behebe die blockierenden Bedingungen, bevor du diesen Change terminierst.',
  'metric.renewNow': 'Renewals in der ersten Stunde erwartet', 'metric.rebindNow': 'Rebinding kann beginnen nach', 'metric.oldLeasesGone': 'Alle alten Leases enden innerhalb',
  'timeline.title': 'Lease-Welle', 'timeline.description': 'Geschätzt anhand gleichmäßig verteilter Zeiten bis zum nächsten Renewal.', 'timeline.renewal': 'T1 Renewal', 'timeline.rebinding': 'T2 Rebinding', 'timeline.expiry': 'Lease-Ablauf', 'timeline.firstHour': 'Etwa {count} Clients erreichen diese Phase in der ersten Stunde', 'timeline.startsAfter': 'Die ersten Clients erreichen diese Phase nach {duration}', 'timeline.allBy': 'Jede aktuelle Lease erreicht sie innerhalb von {duration}',
  'findings.title': 'Was das Risiko bestimmt',
  'finding.livePoolOverlap': 'Beide Server können aus demselben Pool antworten', 'finding.livePoolOverlap.detail': 'Konkurrierende autoritative Server können dieselbe Adresse vergeben. Stoppe einen Dienst oder trenne seinen Pool vor dem Cutover.',
  'finding.relayNotUpdated': 'Ein Relay zeigt noch auf den alten Dienst', 'finding.relayNotUpdated.detail': 'Clients hinter diesem Relay erreichen den Ersatzserver beim Rebinding möglicherweise nicht.',
  'finding.leasesMissingForSharedPool': 'Dem gemeinsamen Pool fehlt der übertragene Lease-Stand', 'finding.leasesMissingForSharedPool.detail': 'Der neue Server erkennt noch belegte Adressen nicht und könnte Duplikate vergeben.',
  'finding.newServerAddress': 'Clients sind auf Rebinding angewiesen, um die neue Adresse zu finden', 'finding.newServerAddress.detail': 'Das erste Unicast-Renewal kann weiter den alten Server ansprechen, bis Clients T2 erreichen oder DHCP neu starten.',
  'finding.temporaryPoolCapacity': 'Der getrennte Ersatzpool braucht genügend freie Kapazität', 'finding.temporaryPoolCapacity.detail': 'Das Kollisionsrisiko sinkt, aber Clients belegen den temporären Pool, während alte Leases gültig bleiben.',
  'finding.offlineClients': 'Offline-Clients können mit altem Lease-Stand zurückkehren', 'finding.offlineClients.detail': 'Zurückkehrende Geräte können nach der sichtbaren Cutover-Welle ihre vorige Adresse anfordern.',
  'finding.leaseChangeNotRetroactive': 'Bestehende Leases behalten ihre ursprüngliche Laufzeit', 'finding.leaseChangeNotRetroactive.detail': 'Erst ein erfolgreiches Renewal oder eine neue Vergabe erhält die Zieldauer.',
  'finding.optionChangeOnRenewal': 'Optionsänderungen kommen beim Renewal oder mit einer neuen Lease an', 'finding.optionChangeOnRenewal.detail': 'Berücksichtige die Lease-Welle, bevor du die neue DNS-Option bei allen Clients erwartest.',
  'finding.emergencyRecovery': 'Ein Notfallersatz verkürzt die Vorbereitung', 'finding.emergencyRecovery.detail': 'Sichere Nachweise und Konfigurationsstand und prüfe Kollisions- sowie Relay-Risiken vor Aktivierung.',
  'finding.none': 'Für die eingegebene Topologie wurde kein zusätzliches Zeitrisiko erkannt.',
  'severity.blocker': 'Blocker', 'severity.warning': 'Warnung', 'severity.info': 'Hinweis',
  'checklist.title': 'Cutover-Checkliste', 'phase.prepare': 'Vorbereiten', 'phase.cutover': 'Umschalten', 'phase.validate': 'Validieren', 'phase.rollback': 'Rollback bereithalten',
  'action.captureScopeOptions': 'Scopes, Reservierungen, Ausschlüsse, Optionen und Autorisierungsstatus dokumentieren.', 'action.backupConfiguration': 'Aktuelle DHCP-Konfiguration exportieren und sicher sichern.', 'action.verifyTargetService': 'Zeit, Autorisierung, Bindings, Firewall und Poolkapazität des Zielservers prüfen.', 'action.verifyLeaseTransfer': 'Übertragene aktive Leases und Reservierungen vor Aktivierung vergleichen.', 'action.stageLeaseReduction': 'Die kürzere Lease früh genug setzen, damit aktuelle Clients vor dem Cutover erneuern.', 'action.verifyRelayPath': 'Alle Relays oder IP-Helper erfassen und den gerouteten Pfad zum Ziel testen.', 'action.freezeDhcpChanges': 'Administrative DHCP-Änderungen einfrieren und den finalen Quellstand sichern.', 'action.stopOldService': 'Alten DHCP-Dienst stoppen oder isolieren, bevor ein überlappender Pool aktiviert wird.', 'action.startTargetService': 'Zieldienst aktivieren und Angebote aus dem vorgesehenen Scope prüfen.', 'action.applyLeaseChange': 'Ziel-Lease-Dauer anwenden und ihre Ausgabe bei einem Test-Renewal bestätigen.', 'action.applyOptionChange': 'Geplante DHCP-Optionsänderung auf die vorgesehenen Scopes anwenden.', 'action.applyRelayTarget': 'Geplante Relay- oder IP-Helper-Ziele anwenden und verifizieren.', 'action.testRenewal': 'Bestehenden Testclient erneuern und Adresse, Gateway, DNS sowie Lease-Dauer prüfen.', 'action.testNewClient': 'Neuen Client ohne vorhandenen Lease-Stand testen.', 'action.monitorDhcpTraffic': 'DHCP Discover, Offer, Request, Acknowledge und Negative Acknowledge überwachen.', 'action.verifyOptions': 'Wirksame DHCP-Optionen auf mindestens einem Client je geroutetem Segment prüfen.', 'action.defineRollbackTrigger': 'Exakte Fehlerschwelle und Entscheider für den Rollback festlegen.', 'action.retainOldServiceState': 'Vorige Konfiguration und Lease-Stand wiederherstellbar halten, bis das alte Lease-Fenster endet.', 'action.retainPreviousConfiguration': 'Vorige Optionswerte und ein getestetes Rücksetzverfahren verfügbar halten.',
  'rollback.title': 'Rollback-Fenster', 'rollback.keepOldServiceRecoverable': 'Alten Dienst wiederherstellbar, aber bis zur Rollback-Entscheidung stumm halten.', 'rollback.restoreRelayTarget': 'Rücksetzen der Relay-Ziele samt Validierungsbefehl dokumentieren.', 'rollback.restorePreviousConfiguration': 'Gesicherte Optionswerte wiederherstellen und das vorige Verhalten mit einem Test-Renewal bestätigen.', 'rollback.validateRollbackClients': 'Nach dem Rollback je kritischem Segment einen erneuernden und einen neuen Client prüfen.',
  'assumptions.title': 'Modellannahmen', 'assumption.uniformRenewalSchedule': 'Vor dem Cutover gelten Online-Clients als gesund und gleichmäßig über ihren T1-Renewal-Zyklus verteilt; bereits fehlschlagende Renewals werden nicht modelliert.', 'assumption.clientBehaviorVaries': 'Client- und Serverimplementierungen können vom Standard-Zeitmodell abweichen.', 'assumption.offlineEstimate': 'Der Anteil offline befindlicher Clients ist eine Betriebsschätzung.',
  'export.copy': 'Plan kopieren', 'export.copied': 'Plan kopiert', 'export.download': 'Markdown herunterladen',
  'privacy.title': 'Deine Daten bleiben hier', 'privacy.description': 'Nur lokal in diesem Browser verarbeitet. Es werden keine Daten hochgeladen. DHCPulse hat kein Backend, keine Analyse, kein Konto und keine Speicherfunktion.',
  'footer.disclaimer': 'Lokale Workbench-Hilfe, kein Ersatz für Herstellerdokumentation oder getestete Betriebsmaßnahmen.', 'footer.rfc': 'Zeitmodell: RFC 2131',
  'preset.safeMigration': 'Windows-DHCP-Migration', 'preset.safeMigration.detail': 'Gleiche Dienstadresse mit übertragenen aktiven Leases.', 'preset.newAddress': 'Neue Serveradresse + Relay', 'preset.newAddress.detail': 'Clients müssen einen Ersatz unter neuer Adresse finden.', 'preset.dnsOption': 'DNS-Option ausrollen', 'preset.dnsOption.detail': 'Schätze, wann Option 6 die Client-Population erreicht.', 'preset.collision': 'Unsichere Überlappung prüfen', 'preset.collision.detail': 'Risiko doppelter Adressvergabe vor dem Cutover sichtbar machen.',
  'duration.minute': 'Minute', 'duration.minutes': 'Minuten', 'duration.hour': 'Stunde', 'duration.hours': 'Stunden', 'duration.day': 'Tag', 'duration.days': 'Tage',
  'export.title': 'DHCPulse-Change-Plan', 'export.scenario': 'Szenario', 'export.assessment': 'Bewertung', 'export.timeline': 'Lease-Zeitachse', 'export.findings': 'Risikohinweise', 'export.checklist': 'Cutover-Checkliste', 'export.rollback': 'Rollback-Hinweise', 'export.assumptions': 'Annahmen', 'export.currentLease': 'Aktuelle Lease', 'export.clients': 'Geschätzte Clients', 'export.generated': 'Lokal mit DHCPulse erstellt. Vor Verwendung prüfen und anpassen.',
};

export const translations = { en, de };

export function translate(locale: Locale, key: CopyKey): string {
  return translations[locale][key];
}

export function interpolate(template: string, values: Record<string, string | number>): string {
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    template,
  );
}
