import { useMemo, useState } from 'react';
import { compareDhcpConfigurations, type ConfigurationChangeImpact, type ConfigurationChangeKind, type ConfigurationEntityType } from '../domain/config-diff';
import { importDhcpConfiguration } from '../domain/config-import';
import type { DhcpConfiguration } from '../domain/config-model';
import { buildWorkbenchReport, downloadWorkbenchReport } from '../domain/workbench-export';
import type { ToolPanelProps } from './ToolPanel';

const MAX_FILE_SIZE=2*1024*1024;
interface SideState{text:string;fileName:string;configuration:DhcpConfiguration|null;error:string}
const empty=():SideState=>({text:'',fileName:'',configuration:null,error:''});
const copy={en:{title:'Redacted configuration comparison',source:'Source configuration',target:'Target configuration',sourceFile:'Source local file',targetFile:'Target local file',importSource:'Import source',importTarget:'Import target',compare:'Compare configurations',reset:'Reset',download:'Download report',result:'Semantic changes',impact:'Impact',kind:'Change kind',entity:'Entity type',all:'All',added:'Added',removed:'Removed',changed:'Changed',empty:'Import both configurations to compare them.',none:'No changes match these filters.',tooLarge:'Files must be 2 MiB or smaller.',assumptions:'Assumptions and limitations',sources:'Authoritative sources'},de:{title:'Redigierter Konfigurationsvergleich',source:'Quellkonfiguration',target:'Zielkonfiguration',sourceFile:'Lokale Quelldatei',targetFile:'Lokale Zieldatei',importSource:'Quelle importieren',importTarget:'Ziel importieren',compare:'Konfigurationen vergleichen',reset:'Zurücksetzen',download:'Bericht herunterladen',result:'Semantische Änderungen',impact:'Auswirkung',kind:'Änderungsart',entity:'Entitätstyp',all:'Alle',added:'Hinzugefügt',removed:'Entfernt',changed:'Geändert',empty:'Importiere beide Konfigurationen für den Vergleich.',none:'Keine Änderungen entsprechen diesen Filtern.',tooLarge:'Dateien dürfen höchstens 2 MiB groß sein.',assumptions:'Annahmen und Grenzen',sources:'Maßgebliche Quellen'}};

export function ConfigDiffTool({locale}:ToolPanelProps){const c=copy[locale];const [before,setBefore]=useState(empty);const [after,setAfter]=useState(empty);const [impact,setImpact]=useState<'all'|ConfigurationChangeImpact>('all');const [kind,setKind]=useState<'all'|ConfigurationChangeKind>('all');const [entity,setEntity]=useState<'all'|ConfigurationEntityType>('all');const [keys,setKeys]=useState([0,0]);
 const importSide=(side:'before'|'after',text:string,fileName='')=>{const setter=side==='before'?setBefore:setAfter;try{const imported=importDhcpConfiguration({text,...(fileName?{fileName}:{})});setter({text:'',fileName,configuration:imported.configuration,error:''});}catch(error){setter(current=>({...current,configuration:null,error:error instanceof Error?error.message:String(error)}));}};
 const onFile=async(side:'before'|'after',file:File|undefined)=>{const setter=side==='before'?setBefore:setAfter;if(!file){setter(empty());return;}if(file.size>MAX_FILE_SIZE){setter({...empty(),error:c.tooLarge});return;}try{const text=await file.text();importSide(side,text,file.name);}catch{setter({...empty(),error:locale==='de'?'Datei konnte nicht gelesen werden.':'The file could not be read.'});}};
 const diff=useMemo(()=>before.configuration&&after.configuration?compareDhcpConfigurations(before.configuration,after.configuration):null,[before.configuration,after.configuration]);const filtered=useMemo(()=>diff?.changes.filter(change=>(impact==='all'||change.impact===impact)&&(kind==='all'||change.kind===kind)&&(entity==='all'||change.entityType===entity))??[],[diff,impact,kind,entity]);
 const reset=()=>{setBefore(empty());setAfter(empty());setImpact('all');setKind('all');setEntity('all');setKeys(([a=0,b=0])=>[a+1,b+1]);};const download=()=>{if(!diff)return;const report=buildWorkbenchReport({toolId:'config-diff',toolName:locale==='de'?'Konfigurationsvergleich':'Configuration comparison',generatedAt:new Date().toISOString(),inputs:{sourceVendor:before.configuration?.metadata.vendor,targetVendor:after.configuration?.metadata.vendor,summary:diff.summary},findings:diff.changes.map(change=>({severity:change.impact,title:`${change.kind} ${change.entityType}`,detail:change.explanation})),assumptions:[locale==='de'?'Werte und Identifikatoren sind im Vergleich und Export redigiert.':'Values and identifiers are redacted in the comparison and export.'],sources:[{label:'DHCP configuration model',url:'https://www.rfc-editor.org/rfc/rfc2131.html'}]});downloadWorkbenchReport(report.markdown,'dhcpulse-config-diff.md');};
 return <div className="workbench-stack" data-testid="tool-panel-config-diff"><section className="planner-card workbench-form" aria-labelledby="diff-title"><h2 id="diff-title">{c.title}</h2><div className="diff-inputs"><Side label={c.source} fileLabel={c.sourceFile} importLabel={c.importSource} state={before} fileKey={keys[0]??0} onText={text=>setBefore(current=>({...current,text,fileName:'',error:''}))} onImport={()=>importSide('before',before.text)} onFile={file=>void onFile('before',file)}/><Side label={c.target} fileLabel={c.targetFile} importLabel={c.importTarget} state={after} fileKey={keys[1]??0} onText={text=>setAfter(current=>({...current,text,fileName:'',error:''}))} onImport={()=>importSide('after',after.text)} onFile={file=>void onFile('after',file)}/></div><div className="workbench-actions"><button type="button" className="secondary-button" onClick={reset}>{c.reset}</button><button type="button" className="primary-button" disabled={!before.text.trim()&&!before.configuration||!after.text.trim()&&!after.configuration} onClick={()=>{if(before.text.trim())importSide('before',before.text);if(after.text.trim())importSide('after',after.text);}}>{c.compare}</button><button type="button" className="primary-button" disabled={!diff} onClick={download}>{c.download}</button></div></section><section className="planner-card workbench-results" role="region" aria-labelledby="diff-result"><h2 id="diff-result">{c.result}</h2>{!diff?<p>{c.empty}</p>:<><div className="filter-row"><Filter label={c.impact} value={impact} onChange={value=>setImpact(value as typeof impact)} options={['all','blocker','warning','info']} c={c}/><Filter label={c.kind} value={kind} onChange={value=>setKind(value as typeof kind)} options={['all','added','removed','changed']} c={c}/><Filter label={c.entity} value={entity} onChange={value=>setEntity(value as typeof entity)} options={['all',...new Set(diff.changes.map(change=>change.entityType))]} c={c}/></div>{filtered.length?<ol className="change-list">{filtered.map(change=><li key={change.id}><span className={`severity finding-${change.impact}`}>{change.impact}</span><strong>{c[change.kind]}</strong><span>{change.entityType}</span><p>{change.explanation}</p></li>)}</ol>:<p>{c.none}</p>}<details className="workbench-section"><summary>{c.assumptions}</summary><p>{locale==='de'?'Semantische Unterschiede basieren auf dem normalisierten, redigierten Modell.':'Semantic differences use the normalized, redacted model.'}</p></details><section className="workbench-section"><h3>{c.sources}</h3><a href="https://www.rfc-editor.org/rfc/rfc2131.html" target="_blank" rel="noreferrer">RFC 2131</a></section></>}</section></div>}

function Side({label,fileLabel,importLabel,state,fileKey,onText,onImport,onFile}:{label:string;fileLabel:string;importLabel:string;state:SideState;fileKey:number;onText:(value:string)=>void;onImport:()=>void;onFile:(file:File|undefined)=>void}){return <fieldset className="diff-side"><legend>{label}</legend><label className="workbench-field"><span>{label}</span><textarea rows={8} value={state.text} onChange={e=>onText(e.target.value)}/></label><label className="workbench-field file-field"><span>{fileLabel}</span><input key={fileKey} type="file" onChange={e=>onFile(e.target.files?.[0])}/></label>{state.fileName&&<p className="file-name">{state.fileName}</p>}{state.error&&<p className="field-error" role="alert">{state.error}</p>}<button type="button" className="secondary-button" disabled={!state.text.trim()} onClick={onImport}>{importLabel}</button>{state.configuration&&<p className="imported-state">✓ {state.configuration.metadata.vendor}</p>}</fieldset>}
function Filter({label,value,onChange,options,c}:{label:string;value:string;onChange:(value:string)=>void;options:string[];c:typeof copy.en}){return <label className="workbench-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(option=><option key={option} value={option}>{option==='all'?c.all:option==='added'?c.added:option==='removed'?c.removed:option==='changed'?c.changed:option}</option>)}</select></label>}
