import { useEffect, useMemo, useRef, useState } from 'react';
import { compareDhcpConfigurations, type ConfigurationChange, type ConfigurationChangeImpact, type ConfigurationChangeKind, type ConfigurationEntityType } from '../domain/config-diff';
import { importDhcpConfiguration } from '../domain/config-import';
import type { DhcpConfigFormat, DhcpConfiguration } from '../domain/config-model';
import { buildWorkbenchReport, downloadWorkbenchReport, type WorkbenchReportSource } from '../domain/workbench-export';
import type { ToolPanelProps } from './ToolPanel';

const MAX_FILE_SIZE = 2 * 1024 * 1024;
const sourcePreset = `subnet 192.0.2.0 netmask 255.255.255.0 {
  range 192.0.2.50 192.0.2.120;
  option routers 192.0.2.1;
}`;
const targetPreset = `{
  "Dhcp4": {
    "subnet4": [{
      "subnet": "192.0.2.0/24",
      "pools": [{ "pool": "192.0.2.60 - 192.0.2.150" }],
      "option-data": [{ "name": "routers", "data": "192.0.2.1" }]
    }]
  }
}`;
type ErrorTarget = 'text' | 'file';
interface SideState { text: string; fileName: string; configuration: DhcpConfiguration | null; error: string; errorTarget: ErrorTarget | null; }
const initialSide = (text: string): SideState => ({ text, fileName: '', configuration: null, error: '', errorTarget: null });
const copy = {
  en: { title: 'Redacted configuration comparison', source: 'Source configuration', target: 'Target configuration', sourceFile: 'Source local file', targetFile: 'Target local file', importSource: 'Import source', importTarget: 'Import target', compare: 'Compare configurations', reset: 'Reset', download: 'Download report', result: 'Semantic changes', summary: 'Change summary', total: 'Total changes', blockers: 'Blockers', warnings: 'Warnings', impact: 'Impact', kind: 'Change kind', entity: 'Entity type', all: 'All', added: 'Added', removed: 'Removed', changed: 'Changed', empty: 'Edit the synthetic source and target examples, then compare them.', none: 'No changes match these filters.', tooLarge: 'Files must be 2 MiB or smaller.', readError: 'The file could not be read.', importError: 'The configuration could not be imported.', assumptions: 'Assumptions and limitations', sources: 'Authoritative sources' },
  de: { title: 'Redigierter Konfigurationsvergleich', source: 'Quellkonfiguration', target: 'Zielkonfiguration', sourceFile: 'Lokale Quelldatei', targetFile: 'Lokale Zieldatei', importSource: 'Quelle importieren', importTarget: 'Ziel importieren', compare: 'Konfigurationen vergleichen', reset: 'Zurücksetzen', download: 'Bericht herunterladen', result: 'Semantische Änderungen', summary: 'Änderungsübersicht', total: 'Änderungen gesamt', blockers: 'Blocker', warnings: 'Warnungen', impact: 'Auswirkung', kind: 'Änderungsart', entity: 'Entitätstyp', all: 'Alle', added: 'Hinzugefügt', removed: 'Entfernt', changed: 'Geändert', empty: 'Bearbeite die synthetischen Quell- und Zielbeispiele und vergleiche sie anschließend.', none: 'Keine Änderungen entsprechen diesen Filtern.', tooLarge: 'Dateien dürfen höchstens 2 MiB groß sein.', readError: 'Die Datei konnte nicht gelesen werden.', importError: 'Die Konfiguration konnte nicht importiert werden.', assumptions: 'Annahmen und Grenzen', sources: 'Maßgebliche Quellen' },
} as const;
const impactRank: Record<ConfigurationChangeImpact, number> = { blocker: 0, warning: 1, info: 2 };

export function ConfigDiffTool({ locale }: ToolPanelProps) {
  const c = copy[locale];
  const [before, setBefore] = useState(() => initialSide(sourcePreset));
  const [after, setAfter] = useState(() => initialSide(targetPreset));
  const [impact, setImpact] = useState<'all' | ConfigurationChangeImpact>('all');
  const [kind, setKind] = useState<'all' | ConfigurationChangeKind>('all');
  const [entity, setEntity] = useState<'all' | ConfigurationEntityType>('all');
  const [keys, setKeys] = useState([0, 0]);
  const generations = useRef({ before: 0, after: 0 });
  useEffect(() => () => { generations.current.before += 1; generations.current.after += 1; }, []);
  const setSide = (side: 'before' | 'after', update: SideState | ((current: SideState) => SideState)) => (side === 'before' ? setBefore : setAfter)(update);
  const importSide = (side: 'before' | 'after', text: string, fileName = '', target: ErrorTarget = 'text') => { try { const imported = importDhcpConfiguration({ text, ...(fileName ? { fileName } : {}) }); setSide(side, { text: '', fileName, configuration: imported.configuration, error: '', errorTarget: null }); } catch { setSide(side, (current) => ({ ...current, configuration: null, error: c.importError, errorTarget: target })); } };
  const onFile = async (side: 'before' | 'after', file: File | undefined) => { const token = ++generations.current[side]; if (!file) { setSide(side, initialSide(side === 'before' ? sourcePreset : targetPreset)); return; } if (file.size > MAX_FILE_SIZE) { setSide(side, { ...initialSide(''), error: c.tooLarge, errorTarget: 'file' }); return; } setSide(side, { text: '', fileName: file.name, configuration: null, error: '', errorTarget: null }); try { const text = await file.text(); if (token !== generations.current[side]) return; importSide(side, text, file.name, 'file'); } catch { if (token !== generations.current[side]) return; setSide(side, { ...initialSide(''), error: c.readError, errorTarget: 'file' }); } };
  const diff = useMemo(() => before.configuration && after.configuration ? compareDhcpConfigurations(before.configuration, after.configuration) : null, [before.configuration, after.configuration]);
  const filtered = useMemo(() => (diff?.changes.filter((change) => (impact === 'all' || change.impact === impact) && (kind === 'all' || change.kind === kind) && (entity === 'all' || change.entityType === entity)) ?? []).sort((left, right) => impactRank[left.impact] - impactRank[right.impact] || left.entityType.localeCompare(right.entityType) || left.id.localeCompare(right.id)), [diff, impact, kind, entity]);
  const reset = () => { generations.current.before += 1; generations.current.after += 1; setBefore(initialSide(sourcePreset)); setAfter(initialSide(targetPreset)); setImpact('all'); setKind('all'); setEntity('all'); setKeys(([a = 0, b = 0]) => [a + 1, b + 1]); };
  const download = () => { if (!diff) return; const report = buildWorkbenchReport({ toolId: 'config-diff', toolName: locale === 'de' ? 'Konfigurationsvergleich' : 'Configuration comparison', generatedAt: new Date().toISOString(), locale, inputs: { sourceVendor: before.configuration?.metadata.vendor, targetVendor: after.configuration?.metadata.vendor, summary: diff.summary }, findings: diff.changes.map((change) => ({ severity: change.impact, title: `${kindLabel(change.kind, locale)} ${entityLabel(change.entityType, locale)}`, detail: changeExplanation(change, locale) })), assumptions: [locale === 'de' ? 'Semantische Werte und Identifikatoren sind im Vergleich und Export redigiert.' : 'Semantic values and identifiers are redacted in the comparison and export.'], sources: diffSources(before.configuration!, after.configuration!, locale), sensitiveValues: [before.fileName, after.fileName] }); downloadWorkbenchReport(report.markdown, 'dhcpulse-config-diff.md'); };
  const onText = (side: 'before' | 'after', text: string) => { generations.current[side] += 1; setSide(side, (current) => ({ ...current, text, fileName: '', configuration: null, error: '', errorTarget: null })); };
  return <div className="workbench-stack" data-testid="tool-panel-config-diff"><section className="planner-card workbench-form" aria-labelledby="diff-title"><h2 id="diff-title">{c.title}</h2><div className="diff-inputs"><Side label={c.source} fileLabel={c.sourceFile} importLabel={c.importSource} state={before} fileKey={keys[0] ?? 0} onText={(text) => onText('before', text)} onImport={() => importSide('before', before.text)} onFile={(file) => void onFile('before', file)} /><Side label={c.target} fileLabel={c.targetFile} importLabel={c.importTarget} state={after} fileKey={keys[1] ?? 0} onText={(text) => onText('after', text)} onImport={() => importSide('after', after.text)} onFile={(file) => void onFile('after', file)} /></div><div className="workbench-actions"><button type="button" className="secondary-button" onClick={reset}>{c.reset}</button><button type="button" className="primary-button" disabled={(!before.text.trim() && !before.configuration) || (!after.text.trim() && !after.configuration)} onClick={() => { if (before.text.trim()) importSide('before', before.text); if (after.text.trim()) importSide('after', after.text); }}>{c.compare}</button><button type="button" className="primary-button" disabled={!diff} onClick={download}>{c.download}</button></div></section>
    <section className="planner-card workbench-results" role="region" aria-labelledby="diff-result"><h2 id="diff-result">{c.result}</h2>{!diff ? <p>{c.empty}</p> : <><section className="workbench-section" aria-labelledby="diff-summary"><h3 id="diff-summary">{c.summary}</h3><div className="metric-grid workbench-metrics"><div className="metric"><span>{c.total}</span><strong>{diff.summary.total}</strong></div><div className="metric"><span>{c.added}</span><strong>{diff.summary.added}</strong></div><div className="metric"><span>{c.removed}</span><strong>{diff.summary.removed}</strong></div><div className="metric"><span>{c.changed}</span><strong>{diff.summary.changed}</strong></div><div className="metric"><span>{c.blockers}</span><strong>{diff.summary.blockers}</strong></div><div className="metric"><span>{c.warnings}</span><strong>{diff.summary.warnings}</strong></div></div></section><div className="filter-row"><Filter label={c.impact} value={impact} onChange={(value) => setImpact(value as typeof impact)} options={['all', 'blocker', 'warning', 'info']} locale={locale} c={c} /><Filter label={c.kind} value={kind} onChange={(value) => setKind(value as typeof kind)} options={['all', 'added', 'removed', 'changed']} locale={locale} c={c} /><Filter label={c.entity} value={entity} onChange={(value) => setEntity(value as typeof entity)} options={['all', ...new Set(diff.changes.map((change) => change.entityType))]} locale={locale} c={c} /></div>{filtered.length ? <ol className="change-list">{filtered.map((change) => <li key={change.id} data-impact={change.impact}><span className={`severity finding-${change.impact}`}>{severityLabel(change.impact, locale)}</span><strong>{kindLabel(change.kind, locale)}</strong><span>{entityLabel(change.entityType, locale)}</span><p>{changeExplanation(change, locale)}</p></li>)}</ol> : <p>{c.none}</p>}<details className="workbench-section"><summary>{c.assumptions}</summary><p>{locale === 'de' ? 'Semantische Unterschiede basieren auf dem normalisierten, redigierten Modell.' : 'Semantic differences use the normalized, redacted model.'}</p></details><section className="workbench-section"><h3>{c.sources}</h3><SourceLinks sources={diffSources(before.configuration, after.configuration, locale)} /></section></>}</section></div>;
}

function Side({ label, fileLabel, importLabel, state, fileKey, onText, onImport, onFile }: { label: string; fileLabel: string; importLabel: string; state: SideState; fileKey: number; onText: (value: string) => void; onImport: () => void; onFile: (file: File | undefined) => void }) { const id = label.replace(/\W/g, '-'); return <fieldset className="diff-side"><legend>{label}</legend><label className="workbench-field"><span>{label}</span><textarea rows={8} value={state.text} aria-invalid={state.errorTarget === 'text'} aria-describedby={state.errorTarget === 'text' ? `${id}-text-error` : undefined} onChange={(event) => onText(event.target.value)} />{state.errorTarget === 'text' && <small id={`${id}-text-error`} className="field-error" role="alert">{state.error}</small>}</label><label className="workbench-field file-field"><span>{fileLabel}</span><input key={fileKey} type="file" aria-invalid={state.errorTarget === 'file'} aria-describedby={state.errorTarget === 'file' ? `${id}-file-error` : undefined} onChange={(event) => onFile(event.target.files?.[0])} />{state.errorTarget === 'file' && <small id={`${id}-file-error`} className="field-error" role="alert">{state.error}</small>}</label>{state.fileName && <p className="file-name">{state.fileName}</p>}<button type="button" className="secondary-button" disabled={!state.text.trim()} onClick={onImport}>{importLabel}</button>{state.configuration && <p className="imported-state">✓ {state.configuration.metadata.vendor}</p>}</fieldset>; }
function Filter({ label, value, onChange, options, locale, c }: { label: string; value: string; onChange: (value: string) => void; options: string[]; locale: 'en' | 'de'; c: typeof copy.en | typeof copy.de }) { return <label className="workbench-field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option} value={option}>{filterLabel(option, locale, c)}</option>)}</select></label>; }
function filterLabel(option: string, locale: 'en' | 'de', c: typeof copy.en | typeof copy.de) { if (option === 'all') return c.all; if (option === 'added' || option === 'removed' || option === 'changed') return c[option]; if (option === 'blocker' || option === 'warning' || option === 'info') return severityLabel(option, locale); return entityLabel(option as ConfigurationEntityType, locale); }
function kindLabel(value: ConfigurationChangeKind, locale: 'en' | 'de') { const labels = locale === 'de' ? { added: 'Hinzugefügt', removed: 'Entfernt', changed: 'Geändert' } : { added: 'Added', removed: 'Removed', changed: 'Changed' }; return labels[value]; }
function severityLabel(value: ConfigurationChangeImpact, locale: 'en' | 'de') { const labels = locale === 'de' ? { blocker: 'Blocker', warning: 'Warnung', info: 'Hinweis' } : { blocker: 'Blocker', warning: 'Warning', info: 'Info' }; return labels[value]; }
function entityLabel(value: ConfigurationEntityType, locale: 'en' | 'de') { if (locale === 'en') return value; const labels: Record<ConfigurationEntityType, string> = { server: 'Server', scope: 'Scope', pool: 'Pool', exclusion: 'Ausschluss', reservation: 'Reservierung', option: 'Option', policy: 'Richtlinie', class: 'Klasse', relay: 'Relay', failover: 'Failover', 'dns-update': 'DNS-Update', audit: 'Audit', capability: 'Funktion', 'duplicate-identifier': 'Doppelte Kennung' }; return labels[value]; }
function changeExplanation(change: ConfigurationChange, locale: 'en' | 'de') { if (locale === 'en') return change.explanation; return `${entityLabel(change.entityType, locale)} wurde ${change.kind === 'added' ? 'hinzugefügt' : change.kind === 'removed' ? 'entfernt' : 'semantisch geändert'}; Auswirkung vor der Migration prüfen.`; }
function diffSources(before: DhcpConfiguration | null, after: DhcpConfiguration | null, locale: 'en' | 'de'): WorkbenchReportSource[] { if (!before || !after) return []; const formats = new Set([before.metadata.source.format, after.metadata.source.format]); const sources: WorkbenchReportSource[] = []; for (const format of formats) sources.push(sourceForFormat(format, locale)); if (formats.has('isc-dhcpd') && formats.has('kea-json')) sources.push({ label: locale === 'de' ? 'Kea-Migrationsleitfaden' : 'Kea migration guidance', url: 'https://kb.isc.org/docs/migrating-from-isc-dhcp-to-kea-dhcp-using-the-migration-assistant' }); return sources; }
function sourceForFormat(format: Exclude<DhcpConfigFormat, 'unknown'>, locale: 'en' | 'de'): WorkbenchReportSource { const sources: Record<Exclude<DhcpConfigFormat, 'unknown'>, WorkbenchReportSource> = { 'isc-dhcpd': { label: 'ISC DHCP configuration reference', url: 'https://kb.isc.org/docs/isc-dhcp-44-manual-pages-dhcpdconf' }, 'kea-json': { label: 'Kea Administrator Reference Manual', url: 'https://kea.readthedocs.io/en/latest/arm/config.html' }, 'microsoft-xml': { label: locale === 'de' ? 'Microsoft-DHCP-Migrationsleitfaden' : 'Microsoft DHCP migration guidance', url: 'https://learn.microsoft.com/en-us/windows-server/networking/technologies/dhcp/migrate-dhcp-server' }, dnsmasq: { label: 'dnsmasq manual', url: 'https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html' } }; return sources[format]; }
function SourceLinks({ sources }: { sources: WorkbenchReportSource[] }) { return <ul>{sources.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.label}</a></li>)}</ul>; }
