import { useEffect, useMemo, useRef, useState } from 'react';
import { ConfigImportError, importDhcpConfiguration } from '../domain/config-import';
import type { DhcpConfigFormat, DhcpConfiguration, ParserWarning } from '../domain/config-model';
import { buildWorkbenchReport, type WorkbenchReport, type WorkbenchReportSource } from '../domain/workbench-export';
import { ReportDownloadActions } from './ReportDownloadActions';
import type { ToolPanelProps } from './ToolPanel';

const MAX_FILE_SIZE = 2 * 1024 * 1024;
const syntheticPreset = `{
  "Dhcp4": {
    "subnet4": [{
      "subnet": "192.0.2.0/24",
      "pools": [{ "pool": "192.0.2.50 - 192.0.2.150" }],
      "option-data": [{ "name": "routers", "data": "192.0.2.1" }]
    }]
  }
}`;
type SelectFormat = 'auto' | Exclude<DhcpConfigFormat, 'unknown'>;
type ErrorTarget = 'text' | 'file';
interface Analysis { configuration: DhcpConfiguration; warnings: ParserWarning[]; report: WorkbenchReport; }
interface FormError { message: string; target: ErrorTarget; }
const copy = {
  en: { title: 'Local configuration analyzer', format: 'Configuration format', auto: 'Auto-detect', text: 'Configuration text', file: 'Local configuration file', analyze: 'Analyze configuration', reset: 'Reset', download: 'Download report', summary: 'Redacted analysis summary', vendor: 'Vendor', scopes: 'Scopes', pools: 'Pools', reservations: 'Reservations', options: 'Options', warnings: 'Parser warnings', observations: 'Migration and security observations', preview: 'Redacted report preview', empty: 'Edit the synthetic example or choose a local file. Nothing is uploaded.', tooLarge: 'Files must be 2 MiB or smaller.', readError: 'The file could not be read.', importError: 'The configuration could not be imported in the selected format.', assumptions: 'Assumptions and limitations', sources: 'Authoritative sources', noWarnings: 'No parser warnings.' },
  de: { title: 'Lokale Konfigurationsanalyse', format: 'Konfigurationsformat', auto: 'Automatisch erkennen', text: 'Konfigurationstext', file: 'Lokale Konfigurationsdatei', analyze: 'Konfiguration analysieren', reset: 'Zurücksetzen', download: 'Bericht herunterladen', summary: 'Redigierte Analyseübersicht', vendor: 'Hersteller', scopes: 'Scopes', pools: 'Pools', reservations: 'Reservierungen', options: 'Optionen', warnings: 'Parserhinweise', observations: 'Migrations- und Sicherheitsbeobachtungen', preview: 'Redigierte Berichtsvorschau', empty: 'Bearbeite das synthetische Beispiel oder wähle eine lokale Datei. Nichts wird hochgeladen.', tooLarge: 'Dateien dürfen höchstens 2 MiB groß sein.', readError: 'Die Datei konnte nicht gelesen werden.', importError: 'Die Konfiguration konnte im gewählten Format nicht importiert werden.', assumptions: 'Annahmen und Grenzen', sources: 'Maßgebliche Quellen', noWarnings: 'Keine Parserhinweise.' },
} as const;

export function ConfigAnalyzerTool({ locale }: ToolPanelProps) {
  const c = copy[locale];
  const [text, setText] = useState(syntheticPreset);
  const [fileName, setFileName] = useState('');
  const [format, setFormat] = useState<SelectFormat>('auto');
  const [analysis, setAnalysis] = useState<Analysis | null>(null);
  const [error, setError] = useState<FormError | null>(null);
  const [fileKey, setFileKey] = useState(0);
  const generation = useRef(0);
  useEffect(() => () => { generation.current += 1; }, []);
  const analyze = (content: string, name?: string, target: ErrorTarget = 'text') => { try { const imported = importDhcpConfiguration({ text: content, ...(name ? { fileName: name } : {}), ...(format === 'auto' ? {} : { format }) }); const summary = summarizeConfiguration(imported.configuration); const findings = [...imported.warnings.map((warning) => ({ severity: 'warning' as const, title: warningText(warning, locale), detail: `${warning.count} ${locale === 'de' ? 'Vorkommen' : 'occurrence(s)'}` })), ...observations(imported.configuration, locale)]; const sources = sourcesForFormat(summary.format, locale); const report = buildWorkbenchReport({ toolId: 'config-analyzer', toolName: locale === 'de' ? 'Konfigurationsanalyse' : 'Configuration analyzer', generatedAt: new Date().toISOString(), locale, inputs: analyzerReportInputs(summary, locale), findings, assumptions: [locale === 'de' ? 'Der Import erfolgt nach bestem Wissen und ersetzt keine Herstellerprüfung.' : 'Import is best-effort and does not replace vendor validation.'], sources, sensitiveValues: [] }); setAnalysis({ configuration: imported.configuration, warnings: imported.warnings, report }); setError(null); setText(''); } catch (caught) { setAnalysis(null); setError({ target, message: translateImportError(caught, c.importError) }); } };
  const onFile = async (file: File | undefined) => { const token = ++generation.current; setError(null); setAnalysis(null); setText(''); if (!file) { setFileName(''); return; } if (file.size > MAX_FILE_SIZE) { setFileName(''); setError({ target: 'file', message: c.tooLarge }); return; } setFileName(file.name); try { const content = await file.text(); if (token !== generation.current) return; analyze(content, file.name, 'file'); } catch { if (token !== generation.current) return; setFileName(''); setError({ target: 'file', message: c.readError }); } };
  const reset = () => { generation.current += 1; setText(syntheticPreset); setFileName(''); setAnalysis(null); setError(null); setFormat('auto'); setFileKey((key) => key + 1); };
  const summary = useMemo(() => analysis ? summarizeConfiguration(analysis.configuration) : null, [analysis]);
  return <div className="workbench-grid" data-testid="tool-panel-config-analyzer"><section className="planner-card workbench-form" aria-labelledby="analyzer-title"><h2 id="analyzer-title">{c.title}</h2>
    <label className="workbench-field"><span>{c.format}</span><select value={format} onChange={(event) => setFormat(event.target.value as SelectFormat)}><option value="auto">{c.auto}</option><option value="microsoft-xml">Microsoft XML</option><option value="kea-json">Kea JSON</option><option value="isc-dhcpd">ISC dhcpd</option><option value="dnsmasq">dnsmasq</option></select></label>
    <label className="workbench-field"><span>{c.text}</span><textarea rows={10} value={text} aria-invalid={error?.target === 'text'} aria-describedby={error?.target === 'text' ? 'analyzer-text-error' : undefined} onChange={(event) => { generation.current += 1; setText(event.target.value); setFileName(''); setError(null); }} />{error?.target === 'text' && <small id="analyzer-text-error" className="field-error" role="alert">{error.message}</small>}</label>
    <label className="workbench-field file-field"><span>{c.file}</span><input key={fileKey} type="file" accept=".json,.xml,.conf,.txt" aria-invalid={error?.target === 'file'} aria-describedby={error?.target === 'file' ? 'analyzer-file-error' : undefined} onChange={(event) => void onFile(event.target.files?.[0])} />{error?.target === 'file' && <small id="analyzer-file-error" className="field-error" role="alert">{error.message}</small>}</label>
    {fileName && <p className="file-name">{fileName}</p>}<div className="workbench-actions"><button type="button" className="secondary-button" onClick={reset}>{c.reset}</button><button type="button" className="primary-button" disabled={!text.trim()} onClick={() => analyze(text)}>{c.analyze}</button><ReportDownloadActions createReport={() => analysis?.report ?? null} filename="dhcpulse-config-analysis" locale={locale} disabled={!analysis} /></div></section>
    <section className="planner-card workbench-results" role="region" aria-labelledby="analyzer-result"><h2 id="analyzer-result">{c.summary}</h2>{!analysis || !summary ? <p>{c.empty}</p> : <><div className="metric-grid workbench-metrics"><div className="metric"><span>{c.vendor}</span><strong>{summary.vendor}</strong></div><div className="metric"><span>{c.scopes}</span><strong data-metric="scopes">{summary.scopes}</strong></div><div className="metric"><span>{c.pools}</span><strong>{summary.pools}</strong></div><div className="metric"><span>{c.reservations}</span><strong>{summary.reservations}</strong></div><div className="metric"><span>{c.options}</span><strong>{summary.options}</strong></div></div><section className="workbench-section"><h3>{c.warnings}</h3>{analysis.warnings.length ? <ul>{analysis.warnings.map((warning, index) => <li key={`${warning.code}-${index}`}>{warningText(warning, locale)} ({warning.count})</li>)}</ul> : <p>{c.noWarnings}</p>}</section><section className="workbench-section"><h3>{c.observations}</h3><ul>{observations(analysis.configuration, locale).map((item) => <li key={item.title}>{item.title}</li>)}</ul></section><details className="workbench-section"><summary>{c.preview}</summary><pre className="report-preview">{analysis.report.markdown}</pre></details><details className="workbench-section"><summary>{c.assumptions}</summary><p>{locale === 'de' ? 'Rohinhalt wird nach erfolgreicher Analyse verworfen; die Vorschau ist redigiert.' : 'Raw content is discarded after analysis; the preview is redacted.'}</p></details><section className="workbench-section"><h3>{c.sources}</h3><SourceLinks sources={sourcesForFormat(summary.format, locale)} /></section></>}</section></div>;
}

function observations(config: DhcpConfiguration, locale: 'en' | 'de') { const values: { severity: 'warning' | 'info'; title: string }[] = []; if (config.failoverRelationships.length === 0) values.push({ severity: 'warning', title: locale === 'de' ? 'Keine Failover-Beziehung im Import erkannt.' : 'No failover relationship was detected in the import.' }); if (!config.auditSettings.some((item) => item.enabled)) values.push({ severity: 'warning', title: locale === 'de' ? 'Aktive Auditprotokollierung wurde nicht erkannt.' : 'Enabled audit logging was not detected.' }); if (config.ipv6Scopes.length > 0) values.push({ severity: 'info', title: locale === 'de' ? 'DHCPv6-Funktionen bei einer Migration separat abgleichen.' : 'Reconcile DHCPv6 capabilities separately during migration.' }); return values; }
function analyzerReportInputs(summary: ReturnType<typeof summarizeConfiguration>, locale: 'en' | 'de') { const keys = locale === 'de' ? { scopes: 'Bereiche', pools: 'Pools', reservations: 'Reservierungen', options: 'Optionen', failover: 'Failover-Beziehungen', audit: 'Auditprotokollierung aktiv' } : { scopes: 'Scopes', pools: 'Pools', reservations: 'Reservations', options: 'Options', failover: 'Failover relationships', audit: 'Audit logging enabled' }; return { [keys.scopes]: summary.scopes, [keys.pools]: summary.pools, [keys.reservations]: summary.reservations, [keys.options]: summary.options, [keys.failover]: summary.failoverRelationships, [keys.audit]: summary.auditLoggingConfigured }; }
function summarizeConfiguration(configuration: DhcpConfiguration) { return { vendor: configuration.metadata.vendor, format: configuration.metadata.source.format, scopes: configuration.ipv4Scopes.length + configuration.ipv6Scopes.length, pools: configuration.pools.length, reservations: configuration.reservations.length, options: configuration.options.length, failoverRelationships: configuration.failoverRelationships.length, auditLoggingConfigured: configuration.auditSettings.some((item) => item.enabled) }; }
function warningText(warning: ParserWarning, locale: 'en' | 'de') { if (locale === 'en') return warning.message; const labels: Record<ParserWarning['code'], string> = { 'unsupported-directive': 'Nicht unterstützte Anweisung erkannt.', 'partial-parse': 'Konfiguration konnte nur teilweise analysiert werden.', 'duplicate-identifier': 'Doppelte Kennung erkannt.' }; return labels[warning.code]; }
function translateImportError(error: unknown, fallback: string) { if (error instanceof ConfigImportError) return fallback; return error instanceof Error && error.message ? fallback : fallback; }
function sourcesForFormat(format: Exclude<DhcpConfigFormat, 'unknown'>, locale: 'en' | 'de'): WorkbenchReportSource[] { const sources: Record<Exclude<DhcpConfigFormat, 'unknown'>, WorkbenchReportSource> = { 'kea-json': { label: 'Kea Administrator Reference Manual', url: 'https://kea.readthedocs.io/en/latest/arm/config.html' }, 'microsoft-xml': { label: locale === 'de' ? 'Microsoft-DHCP-Dokumentation' : 'Microsoft DHCP documentation', url: 'https://learn.microsoft.com/en-us/windows-server/networking/technologies/dhcp/dhcp-top' }, 'isc-dhcpd': { label: 'ISC DHCP configuration reference', url: 'https://kb.isc.org/docs/isc-dhcp-44-manual-pages-dhcpdconf' }, dnsmasq: { label: 'dnsmasq manual', url: 'https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html' } }; return [sources[format]]; }
function SourceLinks({ sources }: { sources: WorkbenchReportSource[] }) { return <ul>{sources.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.label}</a></li>)}</ul>; }
