import { useMemo, useState } from 'react';
import { analyzeDhcpv6 } from '../domain/dhcpv6';
import type { Dhcpv6Finding, Dhcpv6FindingId, Dhcpv6Input, ValidationChecklistItem } from '../domain/types';
import { buildWorkbenchReport, downloadWorkbenchReport } from '../domain/workbench-export';
import type { ToolPanelProps } from './ToolPanel';

const defaults: Dhcpv6Input = { mode: 'prefix-delegation', raFlags: { m: false, o: false, a: true, p: true }, onLinkPrefixLength: 64, delegatedPoolPrefix: 56, delegatedSize: 64, preferredLifetimeSeconds: 3600, validLifetimeSeconds: 7200, t1Seconds: 1800, t2Seconds: 3150, relayUsed: false, relayLinkAddress: null, duidPresent: true, iaidPresent: true, dnsOptionPresent: true, platform: 'kea', windowsFailoverAssumed: false };
const copy = {
  en: { title: 'DHCPv6 and RA model', mode: 'Addressing mode', platform: 'Platform', prefix: 'On-link prefix length', pool: 'Delegated pool prefix', size: 'Delegated prefix length', preferred: 'Preferred lifetime (seconds)', valid: 'Valid lifetime (seconds)', t1: 'T1 (seconds)', t2: 'T2 (seconds)', relay: 'DHCPv6 relay used', link: 'Relay link-address', duid: 'DUID present', iaid: 'IAID present', dns: 'DNS option present', failover: 'Assume Windows DHCPv6 failover', flags: 'RA flags', reset: 'Reset', download: 'Download report', result: 'DHCPv6 result', capacity: 'Delegated /64 prefixes', findings: 'Contradictions and findings', checklist: 'Validation checklist', assumptions: 'Assumptions and limitations', sources: 'Authoritative sources', none: 'No contradictions detected.' },
  de: { title: 'DHCPv6- und RA-Modell', mode: 'Adressierungsmodus', platform: 'Plattform', prefix: 'On-Link-Präfixlänge', pool: 'Delegierter Pool-Präfix', size: 'Delegierte Präfixlänge', preferred: 'Bevorzugte Lebensdauer (Sekunden)', valid: 'Gültige Lebensdauer (Sekunden)', t1: 'T1 (Sekunden)', t2: 'T2 (Sekunden)', relay: 'DHCPv6-Relay verwendet', link: 'Relay-Link-Adresse', duid: 'DUID vorhanden', iaid: 'IAID vorhanden', dns: 'DNS-Option vorhanden', failover: 'Windows-DHCPv6-Failover annehmen', flags: 'RA-Flags', reset: 'Zurücksetzen', download: 'Bericht herunterladen', result: 'DHCPv6-Ergebnis', capacity: 'Delegierte /64-Präfixe', findings: 'Widersprüche und Hinweise', checklist: 'Validierungscheckliste', assumptions: 'Annahmen und Grenzen', sources: 'Maßgebliche Quellen', none: 'Keine Widersprüche erkannt.' },
} as const;

export function Dhcpv6Tool({ locale }: ToolPanelProps) {
  const [input, setInput] = useState(defaults);
  const c = copy[locale];
  const result = useMemo(() => analyzeDhcpv6(input), [input]);
  const set = <K extends keyof Dhcpv6Input>(key: K, value: Dhcpv6Input[K]) => setInput((current) => ({ ...current, [key]: value }));
  const setFlag = (key: keyof Dhcpv6Input['raFlags'], value: boolean) => setInput((current) => ({ ...current, raFlags: { ...current.raFlags, [key]: value } }));
  const numericError = (field: keyof Dhcpv6Input) => { const finding = result.findings.find((item) => item.evidence.some((evidence) => evidence.startsWith(`${field}=`))); return finding ? findingText(finding, locale) : ''; };
  const download = () => { const report = buildWorkbenchReport({ toolId: 'dhcpv6', toolName: 'DHCPv6', generatedAt: new Date().toISOString(), locale, inputs: dhcpv6ReportInputs(input, locale), findings: result.findings.map((finding) => ({ severity: finding.severity, title: findingText(finding, locale), detail: finding.evidence.join('; ') })), assumptions: [defaultRoute(locale)], sources: [{ label: 'RFC 9915', url: 'https://www.rfc-editor.org/rfc/rfc9915.html' }, { label: 'RFC 4861', url: 'https://www.rfc-editor.org/rfc/rfc4861.html' }], sensitiveValues: [input.relayLinkAddress ?? ''] }); downloadWorkbenchReport(report.markdown, 'dhcpulse-dhcpv6-report.md'); };
  const numbers: [string, keyof Dhcpv6Input][] = [[c.prefix, 'onLinkPrefixLength'], [c.pool, 'delegatedPoolPrefix'], [c.size, 'delegatedSize'], [c.preferred, 'preferredLifetimeSeconds'], [c.valid, 'validLifetimeSeconds'], [c.t1, 't1Seconds'], [c.t2, 't2Seconds']];
  return <div className="workbench-grid" data-testid="tool-panel-dhcpv6"><section className="planner-card workbench-form" aria-labelledby="v6-title"><h2 id="v6-title">{c.title}</h2><div className="workbench-fields"><label className="workbench-field"><span>{c.mode}</span><select value={input.mode} onChange={(event) => set('mode', event.target.value as Dhcpv6Input['mode'])}><option value="slaac-only">{locale === 'de' ? 'Nur SLAAC' : 'SLAAC only'}</option><option value="stateless">{locale === 'de' ? 'Zustandsloses DHCPv6' : 'Stateless DHCPv6'}</option><option value="stateful">{locale === 'de' ? 'Zustandsbehaftetes DHCPv6' : 'Stateful DHCPv6'}</option><option value="prefix-delegation">{locale === 'de' ? 'Präfixdelegation' : 'Prefix delegation'}</option></select></label><label className="workbench-field"><span>{c.platform}</span><select value={input.platform} onChange={(event) => set('platform', event.target.value as Dhcpv6Input['platform'])}><option value="windows">Windows</option><option value="kea">Kea</option><option value="router">Router</option></select></label>{numbers.map(([label, key]) => <Number key={key} label={label} value={input[key] as number} onChange={(value) => set(key, value as never)} error={numericError(key)} />)}</div><fieldset className="flag-grid"><legend>{c.flags}</legend>{(['m', 'o', 'a', 'p'] as const).map((flag) => <label key={flag}><input type="checkbox" checked={input.raFlags[flag]} onChange={(event) => setFlag(flag, event.target.checked)} />{flag.toUpperCase()}</label>)}</fieldset>{([[c.relay, 'relayUsed'], [c.duid, 'duidPresent'], [c.iaid, 'iaidPresent'], [c.dns, 'dnsOptionPresent'], [c.failover, 'windowsFailoverAssumed']] as [string, keyof Dhcpv6Input][]).map(([label, key]) => <label className="check-row" key={key}><input type="checkbox" checked={input[key] as boolean} onChange={(event) => set(key, event.target.checked as never)} />{label}</label>)}{input.relayUsed && <label className="workbench-field"><span>{c.link}</span><input value={input.relayLinkAddress ?? ''} aria-invalid={Boolean(result.findings.find((finding) => finding.id === 'dhcpv6-relay-link-address-missing'))} aria-describedby={result.findings.find((finding) => finding.id === 'dhcpv6-relay-link-address-missing') ? 'dhcpv6-relay-error' : undefined} onChange={(event) => set('relayLinkAddress', event.target.value || null)} />{result.findings.find((finding) => finding.id === 'dhcpv6-relay-link-address-missing') && <small id="dhcpv6-relay-error" className="field-error">{findingText(result.findings.find((finding) => finding.id === 'dhcpv6-relay-link-address-missing')!, locale)}</small>}</label>}<div className="workbench-actions"><button type="button" className="secondary-button" onClick={() => setInput(defaults)}>{c.reset}</button><button type="button" className="primary-button" onClick={download}>{c.download}</button></div></section>
    <section className="planner-card workbench-results" role="region" aria-labelledby="v6-result"><div className={`readiness readiness-${result.readiness}`}><span>{c.result}</span><h2 id="v6-result">{readiness(result.readiness, locale)}</h2></div>{result.delegatedPrefixCapacity && <div className="metric"><span>{c.capacity}</span><strong className="metric-value">{result.delegatedPrefixCapacity.display}</strong></div>}<p className="callout">{defaultRoute(locale)}</p><section className="workbench-section"><h3>{c.findings}</h3>{result.findings.length ? <ul className="finding-list-compact">{result.findings.map((finding) => <li key={finding.id} className={`finding-${finding.severity}`}><span className="severity">{severity(finding.severity, locale)}</span><div><strong>{findingText(finding, locale)}</strong><p>{finding.evidence.join('; ')}</p></div></li>)}</ul> : <p>{c.none}</p>}</section><section className="workbench-section"><h3>{c.checklist}</h3><ul>{result.validationChecklist.map((item) => <li key={item.key}>{item.passed ? '✓' : '✕'} {checkText(item, locale)}</li>)}</ul></section><details className="workbench-section"><summary>{c.assumptions}</summary><p>{locale === 'de' ? 'Router Advertisements und DHCPv6 sind getrennte Dienste, die gemeinsam bewertet werden.' : 'Router Advertisements and DHCPv6 are separate services evaluated together.'}</p></details><section className="workbench-section"><h3>{c.sources}</h3><a href="https://www.rfc-editor.org/rfc/rfc9915.html" target="_blank" rel="noreferrer">RFC 9915</a> · <a href="https://www.rfc-editor.org/rfc/rfc4861.html" target="_blank" rel="noreferrer">RFC 4861</a></section></section></div>;
}

function Number({ label, value, onChange, error }: { label: string; value: number; onChange: (value: number) => void; error: string }) { const id = `dhcpv6-${label.replace(/\W/g, '-')}`; return <label className="workbench-field" htmlFor={id}><span>{label}</span><input id={id} type="number" min="0" value={globalThis.Number.isFinite(value) ? value : ''} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} onChange={(event) => onChange(event.target.value === '' ? globalThis.Number.NaN : event.target.valueAsNumber)} />{error && <small id={`${id}-error`} className="field-error">{error}</small>}</label>; }
function dhcpv6ReportInputs(input: Dhcpv6Input, locale: 'en' | 'de') { const label = (de: string, en: string) => locale === 'de' ? de : en; return { [label('On-Link-Präfixlänge', 'On-link prefix length')]: input.onLinkPrefixLength, [label('Delegierter Pool-Präfix', 'Delegated pool prefix')]: input.delegatedPoolPrefix, [label('Delegierte Präfixlänge', 'Delegated prefix length')]: input.delegatedSize, [label('Bevorzugte Lebensdauer', 'Preferred lifetime')]: input.preferredLifetimeSeconds, [label('Gültige Lebensdauer', 'Valid lifetime')]: input.validLifetimeSeconds, T1: input.t1Seconds, T2: input.t2Seconds, [label('Relay verwendet', 'Relay used')]: input.relayUsed, [label('Relay-Adresse angegeben', 'Relay address provided')]: Boolean(input.relayLinkAddress), [label('DUID vorhanden', 'DUID present')]: input.duidPresent, [label('IAID vorhanden', 'IAID present')]: input.iaidPresent, [label('DNS-Option vorhanden', 'DNS option present')]: input.dnsOptionPresent, [label('Windows-Failover angenommen', 'Windows failover assumed')]: input.windowsFailoverAssumed, [label('RA-Flags', 'RA flags')]: { m: input.raFlags.m, o: input.raFlags.o, a: input.raFlags.a, p: input.raFlags.p } }; }
function readiness(value: string, locale: 'en' | 'de') { return locale === 'de' ? ({ ready: 'Bereit', caution: 'Mit Vorsicht', 'no-go': 'Nicht freigeben' } as Record<string, string>)[value] : ({ ready: 'Ready', caution: 'Caution', 'no-go': 'No-go' } as Record<string, string>)[value]; }
function defaultRoute(locale: 'en' | 'de') { return locale === 'de' ? 'Router Advertisements liefern die IPv6-Standardroute; DHCPv6 nicht.' : 'Router Advertisements supply the IPv6 default route; DHCPv6 does not.'; }
const findingDe: Record<Dhcpv6FindingId, string> = { 'dhcpv6-invalid-prefix-length': 'IPv6-Präfixlängen müssen ganze Zahlen von 0 bis 128 sein.', 'dhcpv6-invalid-time-value': 'DHCPv6-Lebensdauern und T1/T2 müssen vorzeichenlose 32-Bit-Ganzzahlen sein.', 'dhcpv6-preferred-lifetime-exceeds-valid': 'Die bevorzugte Lebensdauer darf die gültige Lebensdauer nicht überschreiten.', 'dhcpv6-delegated-prefix-longer-than-request': 'Ein längeres Pool-Präfix kann das angeforderte kürzere Präfix nicht vergeben.', 'dhcpv6-slash64-capacity-unavailable': 'Ein delegiertes Präfix länger als /64 enthält kein vollständiges /64-Subnetz.', 'dhcpv6-stateful-m-flag-missing': 'Zustandsbehaftete Adresskonfiguration benötigt das RA-Managed-Flag.', 'dhcpv6-stateless-o-flag-missing': 'Zustandsloses DHCPv6 benötigt das RA-Other-Configuration-Flag.', 'dhcpv6-slaac-a-flag-missing': 'SLAAC benötigt eine autonome Präfixankündigung.', 'dhcpv6-p-flag-without-prefix-delegation': 'Das P-Signal widerspricht einem Modus ohne Präfixdelegation.', 'dhcpv6-prefix-delegation-signal-missing': 'Für die Präfixdelegation fehlt ein P-, M- oder O-Signal.', 'dhcpv6-client-identity-missing': 'Für die Identitätszuordnung werden Client-DUID und IAID benötigt.', 'dhcpv6-relay-link-address-missing': 'Zur Auswahl des nachgelagerten Links wird eine Relay-Link-Adresse benötigt.', 'dhcpv6-windows-failover-assumed': 'Windows-DHCP-Failover schützt keinen DHCPv6-Dienst.', 'dhcpv6-t1-not-before-t2': 'T1 sollte vor T2 liegen.', 'dhcpv6-t2-not-before-valid-lifetime': 'T2 sollte vor Ablauf der gültigen Lebensdauer liegen.' };
function findingText(finding: Dhcpv6Finding, locale: 'en' | 'de') { return locale === 'de' ? findingDe[finding.id] : finding.rationale; }
function severity(value: Dhcpv6Finding['severity'], locale: 'en' | 'de') { const labels = locale === 'de' ? { blocker: 'Blocker', warning: 'Warnung', info: 'Hinweis' } : { blocker: 'Blocker', warning: 'Warning', info: 'Info' }; return labels[value]; }
function checkText(item: ValidationChecklistItem, locale: 'en' | 'de') { if (locale === 'en') return item.rationale; const labels: Record<string, string> = { 'preferred-valid-lifetimes': 'Bevorzugte und gültige Lebensdauer sind gültig geordnet.', 't1-t2-order': 'T1 überschreitet T2 nicht.', 't2-valid-lifetime': 'T2 überschreitet die gültige Lebensdauer nicht.', 'on-link-prefix': 'Die On-Link-Präfixlänge liegt im IPv6-Bereich.', 'client-duid': 'Für zustandsbehaftete Zuordnungen ist eine DUID vorhanden.', 'client-iaid': 'Für zustandsbehaftete Zuordnungen ist eine IAID vorhanden.', 'dns-option': 'Die DNS-Option ist vorhanden, wenn DHCPv6 sie liefern soll.', 'relay-link-address': 'Beim Relay-Betrieb ist eine Link-Adresse vorhanden.' }; return labels[item.key] ?? 'Prüfpunkt anhand der verknüpften RFC-Quelle validieren.'; }
