import { useMemo, useState } from 'react';
import { analyzeDhcpv6 } from '../domain/dhcpv6';
import type { Dhcpv6Input } from '../domain/types';
import { buildWorkbenchReport, downloadWorkbenchReport } from '../domain/workbench-export';
import type { ToolPanelProps } from './ToolPanel';

const defaults: Dhcpv6Input = { mode: 'prefix-delegation', raFlags: { m: false, o: false, a: true, p: true }, onLinkPrefixLength: 64, delegatedPoolPrefix: 56, delegatedSize: 64, preferredLifetimeSeconds: 3600, validLifetimeSeconds: 7200, t1Seconds: 1800, t2Seconds: 3150, relayUsed: false, relayLinkAddress: null, duidPresent: true, iaidPresent: true, dnsOptionPresent: true, platform: 'kea', windowsFailoverAssumed: false };
const copy = { en: { title: 'DHCPv6 and RA model', mode: 'Addressing mode', platform: 'Platform', prefix: 'On-link prefix length', pool: 'Delegated pool prefix', size: 'Delegated prefix length', preferred: 'Preferred lifetime (seconds)', valid: 'Valid lifetime (seconds)', t1: 'T1 (seconds)', t2: 'T2 (seconds)', relay: 'DHCPv6 relay used', link: 'Relay link-address', duid: 'DUID present', iaid: 'IAID present', dns: 'DNS option present', reset: 'Reset', download: 'Download report', result: 'DHCPv6 result', capacity: 'Delegated /64 prefixes', findings: 'Contradictions and findings', checklist: 'Validation checklist', assumptions: 'Assumptions and limitations', sources: 'Authoritative sources' }, de: { title: 'DHCPv6- und RA-Modell', mode: 'Adressierungsmodus', platform: 'Plattform', prefix: 'On-Link-Präfixlänge', pool: 'Delegierter Pool-Präfix', size: 'Delegierte Präfixlänge', preferred: 'Bevorzugte Lebensdauer (Sekunden)', valid: 'Gültige Lebensdauer (Sekunden)', t1: 'T1 (Sekunden)', t2: 'T2 (Sekunden)', relay: 'DHCPv6-Relay verwendet', link: 'Relay-Link-Address', duid: 'DUID vorhanden', iaid: 'IAID vorhanden', dns: 'DNS-Option vorhanden', reset: 'Zurücksetzen', download: 'Bericht herunterladen', result: 'DHCPv6-Ergebnis', capacity: 'Delegierte /64-Präfixe', findings: 'Widersprüche und Hinweise', checklist: 'Validierungscheckliste', assumptions: 'Annahmen und Grenzen', sources: 'Maßgebliche Quellen' } };

export function Dhcpv6Tool({ locale }: ToolPanelProps) {
  const [input,setInput] = useState(defaults); const c=copy[locale]; const result=useMemo(()=>analyzeDhcpv6(input),[input]);
  const set=<K extends keyof Dhcpv6Input>(key:K,value:Dhcpv6Input[K])=>setInput(current=>({...current,[key]:value}));
  const setFlag=(key:keyof Dhcpv6Input['raFlags'],value:boolean)=>setInput(current=>({...current,raFlags:{...current.raFlags,[key]:value}}));
  const download=()=>{const report=buildWorkbenchReport({toolId:'dhcpv6',toolName:'DHCPv6',generatedAt:new Date().toISOString(),inputs:input as unknown as Record<string,unknown>,findings:result.findings.map(f=>({severity:f.severity,title:f.rationale,detail:f.evidence.join('; ')})),assumptions:[result.defaultRouteExplanation],sources:[{label:'RFC 8415',url:'https://www.rfc-editor.org/rfc/rfc8415.html'},{label:'RFC 4861',url:'https://www.rfc-editor.org/rfc/rfc4861.html'}]});downloadWorkbenchReport(report.markdown,'dhcpulse-dhcpv6-report.md');};
  return <div className="workbench-grid" data-testid="tool-panel-dhcpv6"><section className="planner-card workbench-form" aria-labelledby="v6-title"><h2 id="v6-title">{c.title}</h2><div className="workbench-fields"><label className="workbench-field"><span>{c.mode}</span><select value={input.mode} onChange={e=>set('mode',e.target.value as Dhcpv6Input['mode'])}><option value="slaac-only">SLAAC only</option><option value="stateless">Stateless DHCPv6</option><option value="stateful">Stateful DHCPv6</option><option value="prefix-delegation">Prefix delegation</option></select></label><label className="workbench-field"><span>{c.platform}</span><select value={input.platform} onChange={e=>set('platform',e.target.value as Dhcpv6Input['platform'])}><option value="windows">Windows</option><option value="kea">Kea</option><option value="router">Router</option></select></label>{([[c.prefix,'onLinkPrefixLength'],[c.pool,'delegatedPoolPrefix'],[c.size,'delegatedSize'],[c.preferred,'preferredLifetimeSeconds'],[c.valid,'validLifetimeSeconds'],[c.t1,'t1Seconds'],[c.t2,'t2Seconds']] as [string,keyof Dhcpv6Input][]).map(([label,key])=><Number key={key} label={label} value={input[key] as number} onChange={value=>set(key,value as never)}/>)}</div><fieldset className="flag-grid"><legend>RA flags</legend>{(['m','o','a','p'] as const).map(flag=><label key={flag}><input type="checkbox" checked={input.raFlags[flag]} onChange={e=>setFlag(flag,e.target.checked)}/>{flag.toUpperCase()}</label>)}</fieldset>{([[c.relay,'relayUsed'],[c.duid,'duidPresent'],[c.iaid,'iaidPresent'],[c.dns,'dnsOptionPresent'],['Assume Windows DHCPv6 failover','windowsFailoverAssumed']] as [string,keyof Dhcpv6Input][]).map(([label,key])=><label className="check-row" key={key}><input type="checkbox" checked={input[key] as boolean} onChange={e=>set(key,e.target.checked as never)}/>{label}</label>)}{input.relayUsed&&<label className="workbench-field"><span>{c.link}</span><input value={input.relayLinkAddress??''} onChange={e=>set('relayLinkAddress',e.target.value||null)}/></label>}<div className="workbench-actions"><button type="button" className="secondary-button" onClick={()=>setInput(defaults)}>{c.reset}</button><button type="button" className="primary-button" onClick={download}>{c.download}</button></div></section>
  <section className="planner-card workbench-results" role="region" aria-labelledby="v6-result"><div className={`readiness readiness-${result.readiness}`}><span>{c.result}</span><h2 id="v6-result">{result.readiness}</h2></div>{result.delegatedPrefixCapacity&&<div className="metric"><span>{c.capacity}</span><strong className="metric-value">{result.delegatedPrefixCapacity.display}</strong></div>}<p className="callout">{result.defaultRouteExplanation}</p><section className="workbench-section"><h3>{c.findings}</h3>{result.findings.length?<ul className="finding-list-compact">{result.findings.map(f=><li key={f.id} className={`finding-${f.severity}`}><span className="severity">{f.severity}</span><div><strong>{f.rationale}</strong><p>{f.evidence.join('; ')}</p></div></li>)}</ul>:<p>{locale==='de'?'Keine Widersprüche erkannt.':'No contradictions detected.'}</p>}</section><section className="workbench-section"><h3>{c.checklist}</h3><ul>{result.validationChecklist.map(item=><li key={item.key}>{item.passed?'✓':'✕'} {item.rationale}</li>)}</ul></section><details className="workbench-section"><summary>{c.assumptions}</summary><p>{locale==='de'?'Router Advertisements und DHCPv6 werden getrennt, aber gemeinsam bewertet.':'Router Advertisements and DHCPv6 are separate services evaluated together.'}</p></details><section className="workbench-section"><h3>{c.sources}</h3><a href="https://www.rfc-editor.org/rfc/rfc8415.html" target="_blank" rel="noreferrer">RFC 8415</a> · <a href="https://www.rfc-editor.org/rfc/rfc4861.html" target="_blank" rel="noreferrer">RFC 4861</a></section></section></div>;
}
function Number({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label className="workbench-field"><span>{label}</span><input type="number" min="0" value={value} onChange={e=>onChange(e.target.valueAsNumber||0)}/></label>;}
