import { useMemo, useState } from 'react';
import { diagnoseDhcp } from '../domain/diagnostics';
import type { DiagnosticCauseId, DhcpDiagnosticInput, DhcpDiagnosticSymptom, DhcpSecurityFindingId } from '../domain/types';
import { buildWorkbenchReport, downloadWorkbenchReport } from '../domain/workbench-export';
import type { ToolPanelProps } from './ToolPanel';

const security: DhcpDiagnosticInput['security'] = { dhcpSnoopingEnabled: true, serverFacingPortsTrusted: true, option82Trusted: true, dnsUpdateCredentialsAligned: true, auditLoggingEnabled: true, windowsDhcpAuthorized: true, raGuardEnabled: true, backupRestoreTested: true, secretExposureDetected: false };
const defaults: DhcpDiagnosticInput = { symptoms: ['no-offer'], path: 'relay', affectedVlans: 'some', existingClientsAffected: false, newClientsAffected: true, serverPlatform: 'windows', recentChange: false, offerSeen: false, requestSeen: false, ackSeen: false, nakSeen: false, declineSeen: false, relayGiaddr: null, relayLinkAddress: null, serverIds: [], freePoolPercentage: 50, dnsQueueSymptoms: false, failoverState: 'normal', security };
const copy = {
  en: { title: 'Progressive DHCP diagnostics', symptom: 'Primary symptom', path: 'Client path', direct: 'Direct', relay: 'Relay', vlans: 'Affected VLANs', some: 'Some', all: 'All', pool: 'Free pool percentage', offer: 'DHCPOFFER observed', request: 'DHCPREQUEST observed', ack: 'DHCPACK observed', recent: 'Recent change', more: 'More evidence', serverIds: 'Server identifiers', reset: 'Reset', download: 'Download report', result: 'Ranked causes', evidence: 'Matched evidence', checks: 'Ordered evidence checks', filters: 'Wireshark filters', commands: 'Read-only commands', security: 'Related security findings', assumptions: 'Assumptions and limitations', sources: 'Authoritative sources', noGaps: 'No related gaps from the evidence.' },
  de: { title: 'Progressive DHCP-Diagnose', symptom: 'Primäres Symptom', path: 'Client-Pfad', direct: 'Direkt', relay: 'Relay', vlans: 'Betroffene VLANs', some: 'Einige', all: 'Alle', pool: 'Freier Pool in Prozent', offer: 'DHCPOFFER beobachtet', request: 'DHCPREQUEST beobachtet', ack: 'DHCPACK beobachtet', recent: 'Kürzliche Änderung', more: 'Weitere Nachweise', serverIds: 'Server-Kennungen', reset: 'Zurücksetzen', download: 'Bericht herunterladen', result: 'Priorisierte Ursachen', evidence: 'Passende Nachweise', checks: 'Geordnete Nachweisprüfungen', filters: 'Wireshark-Filter', commands: 'Schreibgeschützte Befehle', security: 'Zugehörige Sicherheitshinweise', assumptions: 'Annahmen und Grenzen', sources: 'Maßgebliche Quellen', noGaps: 'Keine zugehörigen Lücken aus den Nachweisen.' },
} as const;

export function DiagnosticsTool({ locale }: ToolPanelProps) {
  const [input, setInput] = useState(defaults);
  const c = copy[locale];
  const result = useMemo(() => diagnoseDhcp(input), [input]);
  const set = <K extends keyof DhcpDiagnosticInput>(key: K, value: DhcpDiagnosticInput[K]) => setInput((current) => ({ ...current, [key]: value }));
  const poolError = result.validationFindings[0] ? validationText(locale) : '';
  const download = () => { const report = buildWorkbenchReport({ toolId: 'diagnostics', toolName: locale === 'de' ? 'Diagnose' : 'Diagnostics', generatedAt: new Date().toISOString(), locale, inputs: { [locale === 'de' ? 'Symptome' : 'Symptoms']: input.symptoms.length, [locale === 'de' ? 'Alle VLANs betroffen' : 'All VLANs affected']: input.affectedVlans === 'all', [locale === 'de' ? 'Serverkennungen' : 'Server identifiers']: input.serverIds.length, [locale === 'de' ? 'Offer gesehen' : 'Offer seen']: input.offerSeen, [locale === 'de' ? 'Request gesehen' : 'Request seen']: input.requestSeen, [locale === 'de' ? 'ACK gesehen' : 'ACK seen']: input.ackSeen, [locale === 'de' ? 'Relay-Adresse angegeben' : 'Relay address provided']: Boolean(input.relayGiaddr || input.relayLinkAddress) }, findings: [...result.rankedCauses.map((cause) => ({ severity: 'warning' as const, title: causeTitle(cause.id, locale), detail: causeRationale(cause.id, locale) })), ...result.securityFindings.map((finding) => ({ severity: finding.severity, title: securityText(finding.id, locale) }))], assumptions: [locale === 'de' ? 'Die Rangfolge ist nachvollziehbar und basiert nur auf den eingegebenen Nachweisen.' : 'Ranking is explainable and uses only the evidence entered.'], sources: [...new Map([...result.rankedCauses.map((cause) => [cause.source, { label: causeTitle(cause.id, locale), url: cause.source }] as const), ...result.evidenceSteps.map((step, index) => [step.source, { label: `${locale === 'de' ? 'Prüfung' : 'Check'} ${index + 1}`, url: step.source }] as const)]).values()], sensitiveValues: [input.relayGiaddr ?? '', input.relayLinkAddress ?? '', ...input.serverIds, input.failoverState ?? ''] }); downloadWorkbenchReport(report.markdown, 'dhcpulse-diagnostics-report.md'); };
  return <div className="workbench-grid" data-testid="tool-panel-diagnostics"><section className="planner-card workbench-form" aria-labelledby="diag-title"><h2 id="diag-title">{c.title}</h2><div className="workbench-fields"><label className="workbench-field"><span>{c.symptom}</span><select value={input.symptoms[0]} onChange={(event) => set('symptoms', [event.target.value as DhcpDiagnosticSymptom])}>{symptoms.map(([id, name]) => <option key={id} value={id}>{locale === 'de' ? name[1] : name[0]}</option>)}</select></label><label className="workbench-field"><span>{c.path}</span><select value={input.path} onChange={(event) => set('path', event.target.value as 'direct' | 'relay')}><option value="direct">{c.direct}</option><option value="relay">{c.relay}</option></select></label><label className="workbench-field"><span>{c.vlans}</span><select value={input.affectedVlans} onChange={(event) => set('affectedVlans', event.target.value as 'all' | 'some')}><option value="some">{c.some}</option><option value="all">{c.all}</option></select></label><label className="workbench-field"><span>{c.pool}</span><input type="number" min="0" max="100" value={Number.isFinite(input.freePoolPercentage) ? input.freePoolPercentage : ''} aria-invalid={Boolean(poolError)} aria-describedby={poolError ? 'diagnostics-pool-error' : undefined} onChange={(event) => set('freePoolPercentage', event.target.valueAsNumber)} />{poolError && <small id="diagnostics-pool-error" className="field-error">{poolError}</small>}</label></div>{([[c.offer, 'offerSeen'], [c.request, 'requestSeen'], [c.ack, 'ackSeen'], [c.recent, 'recentChange']] as [string, keyof DhcpDiagnosticInput][]).map(([label, key]) => <label className="check-row" key={key}><input type="checkbox" checked={input[key] as boolean} onChange={(event) => set(key, event.target.checked as never)} />{label}</label>)}<details className="progressive-fields"><summary>{c.more}</summary><label className="workbench-field"><span>giaddr</span><input value={input.relayGiaddr ?? ''} onChange={(event) => set('relayGiaddr', event.target.value || null)} /></label><label className="workbench-field"><span>{c.serverIds}</span><input value={input.serverIds.join(', ')} onChange={(event) => set('serverIds', event.target.value.split(',').map((value) => value.trim()).filter(Boolean))} /></label></details><div className="workbench-actions"><button type="button" className="secondary-button" onClick={() => setInput(defaults)}>{c.reset}</button><button type="button" className="primary-button" onClick={download}>{c.download}</button></div></section>
    <section className="planner-card workbench-results" role="region" aria-labelledby="diag-result"><h2 id="diag-result">{c.result}</h2><ol className="ranked-causes">{result.rankedCauses.map((cause) => <li key={cause.id}><strong>{causeTitle(cause.id, locale)}</strong><p>{causeRationale(cause.id, locale)}</p><a href={cause.source} target="_blank" rel="noreferrer">{locale === 'de' ? 'Quelle zur Ursache' : 'Cause source'}</a><details><summary>{c.evidence}</summary><ul>{cause.matchedEvidence.map((item) => <li key={item}><code>{item}</code></li>)}</ul></details></li>)}</ol><section className="workbench-section"><h3>{c.checks}</h3><ol>{result.evidenceSteps.map((step, index) => <li key={step.id}>{stepText(step.id, locale)} <a href={step.source} target="_blank" rel="noreferrer">{locale === 'de' ? `Quelle für Prüfung ${index + 1}` : `Source for check ${index + 1}`}</a></li>)}</ol></section><section className="workbench-section"><h3>{c.filters}</h3><ul className="code-list">{result.wiresharkFilters.map((filter) => <li key={filter}><code>{filter}</code></li>)}</ul></section><section className="workbench-section"><h3>{c.commands}</h3><ul className="code-list">{result.commands.map((command) => <li key={command}><code>{command}</code></li>)}</ul></section><section className="workbench-section"><h3>{c.security}</h3>{result.securityFindings.length ? <ul>{result.securityFindings.map((finding) => <li key={finding.id}>{securityText(finding.id, locale)}</li>)}</ul> : <p>{c.noGaps}</p>}</section><details className="workbench-section"><summary>{c.assumptions}</summary><p>{locale === 'de' ? 'Die Rangfolge ersetzt keine Paket- und Serverprüfung.' : 'The ranking does not replace packet and server validation.'}</p></details><section className="workbench-section"><h3>{c.sources}</h3><ul>{[...new Map(result.evidenceSteps.map((step) => [step.source, step])).values()].map((step) => <li key={step.source}><a href={step.source} target="_blank" rel="noreferrer">{locale === 'de' ? 'Dokumentation zur Nachweisprüfung' : 'Evidence-check documentation'}</a></li>)}</ul></section></section></div>;
}

const symptoms: [DhcpDiagnosticSymptom, [string, string]][] = [['apipa', ['APIPA address', 'APIPA-Adresse']], ['no-offer', ['No DHCPOFFER', 'Kein DHCPOFFER']], ['wrong-subnet', ['Wrong subnet', 'Falsches Subnetz']], ['wrong-options', ['Wrong options', 'Falsche Optionen']], ['renewal-failure', ['Renewal failure', 'Renewal-Fehler']], ['relay-failure', ['Relay failure', 'Relay-Fehler']], ['pxe-failure', ['PXE failure', 'PXE-Fehler']], ['dns-registration', ['DNS registration', 'DNS-Registrierung']], ['duplicate-address', ['Duplicate address', 'Doppelte Adresse']], ['pool-exhaustion', ['Pool exhaustion', 'Pool-Erschöpfung']], ['failover-state', ['Failover state', 'Failover-Status']], ['rogue-server', ['Rogue server', 'Fremder Server']], ['dhcpv6-ra', ['DHCPv6/RA mismatch', 'DHCPv6/RA-Widerspruch']]];
const causeDe: Record<DiagnosticCauseId, [string, string]> = { 'relay-path-unreachable': ['Relay-Pfad oder Server nicht erreichbar', 'Weitergeleitete Anfragen ohne Angebot weisen zuerst auf Relay, Routing oder den serverseitigen Pfad.'], 'dhcp-server-unreachable': ['DHCP-Server nicht verfügbar oder erreichbar', 'Ein Discover ohne Offer kann bedeuten, dass kein geeigneter Server die Anfrage erhalten oder beantwortet hat.'], 'rogue-or-duplicate-server': ['Fremder oder doppelter DHCP-Server', 'Mehrere Server-Kennungen deuten auf konkurrierende Antwortdienste hin.'], 'address-pool-exhaustion': ['Adresspool erschöpft oder blockiert', 'Geringe freie Kapazität und DECLINE-Aktivität können die Vergabe verhindern.'], 'dns-update-failure': ['Dynamisches DNS-Update fehlgeschlagen', 'Registrierungsfehler weisen auf den DHCP-zu-DNS-Updatepfad.'], 'failover-state-degraded': ['Failover-Beziehungsstatus beeinträchtigt', 'Ein nicht normaler Partnerstatus kann Lease-Eigentum und Dienstverhalten ändern.'], 'scope-or-relay-selection-mismatch': ['Scope- oder Relay-Auswahl stimmt nicht', 'Falsches Subnetz oder NAK kann auf giaddr, Link-Adresse oder Scope-Zuordnung hinweisen.'], 'option-delivery-mismatch': ['DHCP-Optionen stimmen nicht', 'Scope, Reservierung, Klasse oder Richtlinie liefert möglicherweise nicht die erwarteten Optionen.'], 'renewal-path-failure': ['Renewal- oder Rebinding-Pfad fehlgeschlagen', 'Bestehende Clients scheitern, wenn kein geeigneter Server erreichbar ist.'], 'pxe-policy-mismatch': ['PXE-Richtlinie oder Bootoption stimmt nicht', 'Architektur, Klasse, Bootserver oder Bootdatei können falsch zugeordnet sein.'], 'dhcpv6-ra-mismatch': ['DHCPv6 und Router Advertisement widersprechen sich', 'RA-Flags, Präfixdaten und DHCPv6-Modus müssen zusammenpassen.'], 'duplicate-address-detection': ['Doppelte Adresse oder veralteter Lease-Stand', 'DECLINE- oder Doppeladressnachweise können einen Konflikt identifizieren.'] };
function causeTitle(id: DiagnosticCauseId, locale: 'en' | 'de') { if (locale === 'de') return causeDe[id][0]; return diagnoseDhcp({ ...defaults, symptoms: causeSymptom(id) }).rankedCauses.find((cause) => cause.id === id)?.title ?? id; }
function causeRationale(id: DiagnosticCauseId, locale: 'en' | 'de') { if (locale === 'de') return causeDe[id][1]; return diagnoseDhcp({ ...defaults, symptoms: causeSymptom(id) }).rankedCauses.find((cause) => cause.id === id)?.rationale ?? 'Review the matched evidence.'; }
function causeSymptom(id: DiagnosticCauseId): DhcpDiagnosticSymptom[] { const map: Record<DiagnosticCauseId, DhcpDiagnosticSymptom> = { 'relay-path-unreachable': 'relay-failure', 'dhcp-server-unreachable': 'no-offer', 'rogue-or-duplicate-server': 'rogue-server', 'address-pool-exhaustion': 'pool-exhaustion', 'dns-update-failure': 'dns-registration', 'failover-state-degraded': 'failover-state', 'scope-or-relay-selection-mismatch': 'wrong-subnet', 'option-delivery-mismatch': 'wrong-options', 'renewal-path-failure': 'renewal-failure', 'pxe-policy-mismatch': 'pxe-failure', 'dhcpv6-ra-mismatch': 'dhcpv6-ra', 'duplicate-address-detection': 'duplicate-address' }; return [map[id]]; }
function stepText(id: string, locale: 'en' | 'de') { const de: Record<string, string> = { 'inspect-client-configuration': 'Client-Adresse, Lease, Gateway, DNS-Server und DHCP-Serverkennung erfassen.', 'inspect-existing-exchange': 'Vorhandene Paketaufzeichnung auf DISCOVER, OFFER, REQUEST, ACK, NAK und DECLINE prüfen.', 'inspect-relay-selection': 'Beobachtete giaddr oder Link-Adresse mit VLAN und Relay-Pfad vergleichen.', 'inspect-dns-update-events': 'DHCP-Audit- und DNS-Ereignisprotokolle auf Update- und Anmeldefehler prüfen.', 'inspect-scope-capacity': 'Scope-Statistik, Ausschlüsse, Reservierungen, Leases und DECLINE-Einträge prüfen.', 'inspect-failover-state': 'Partnerstatus, letzten Übergang, MCLT und Replikation prüfen.' }; if (locale === 'de') return de[id] ?? 'Nachweis anhand der verknüpften Quelle prüfen.'; const step = diagnoseDhcp(defaults).evidenceSteps.find((item) => item.id === id); return step?.instruction ?? 'Review the evidence using the linked source.'; }
function securityText(id: DhcpSecurityFindingId, locale: 'en' | 'de') { return locale === 'de' ? `Sicherheitslücke prüfen: ${id.replace(/^security-/, '').replaceAll('-', ' ')}` : `Review security finding: ${id.replace(/^security-/, '').replaceAll('-', ' ')}`; }
function validationText(locale: 'en' | 'de') { return locale === 'de' ? 'Der freie Pool muss als Prozentwert von 0 bis 100 angegeben werden.' : 'Free pool percentage must be between 0 and 100.'; }
