import { useMemo, useState } from 'react';
import { analyzeWindowsFailover } from '../domain/failover';
import type { ValidationChecklistItem, WindowsFailoverFinding, WindowsFailoverFindingId, WindowsFailoverInput } from '../domain/types';
import { buildWorkbenchReport } from '../domain/workbench-export';
import { ReportDownloadActions } from './ReportDownloadActions';
import type { ToolPanelProps } from './ToolPanel';

const defaults: WindowsFailoverInput = { mode: 'load-balance', mcltMinutes: 60, stateSwitchoverMinutes: 90, partnerReachable: true, clientsReachBothPartners: true, tcp647Allowed: true, clockSkewSeconds: 10, sameDnsUpdateCredentials: true, configurationReplicated: true, duplicateRelayForwarding: false, scopeProtocol: 'dhcpv4', loadBalancePercentage: 50, reservePercentage: 5, plannedOutageMinutes: 120 };
const copy = {
  en: { title: 'Windows DHCP failover readiness', mode: 'Failover mode', load: 'Load balance', standby: 'Hot standby', protocol: 'Scope protocol', mclt: 'MCLT (minutes)', switchover: 'State switchover (minutes)', skew: 'Clock skew (seconds)', outage: 'Planned outage (minutes)', loadPercent: 'Load-balance percentage', reserve: 'Hot-standby reserve percentage', partner: 'Partner is reachable', clients: 'Clients can reach both partners', port: 'TCP port 647 allowed between partners', dns: 'DNS update credentials match', replication: 'Configuration is replicated', relay: 'Relay forwards duplicate requests', reset: 'Reset', download: 'Download report', result: 'Readiness result', timeline: 'Transition timeline', checklist: 'Validation checklist', findings: 'Findings', assumptions: 'Assumptions and limitations', sources: 'Authoritative sources', minute: 'min' },
  de: { title: 'Bereitschaft für Windows-DHCP-Failover', mode: 'Failover-Modus', load: 'Lastverteilung', standby: 'Hot-Standby', protocol: 'Scope-Protokoll', mclt: 'MCLT (Minuten)', switchover: 'Statuswechsel (Minuten)', skew: 'Zeitabweichung (Sekunden)', outage: 'Geplanter Ausfall (Minuten)', loadPercent: 'Anteil der Lastverteilung', reserve: 'Reserveanteil im Hot-Standby', partner: 'Partner ist erreichbar', clients: 'Clients erreichen beide Partner', port: 'TCP-Port 647 zwischen Partnern erlaubt', dns: 'DNS-Update-Anmeldedaten stimmen überein', replication: 'Konfiguration ist repliziert', relay: 'Relay leitet Anfragen doppelt weiter', reset: 'Zurücksetzen', download: 'Bericht herunterladen', result: 'Bereitschaftsergebnis', timeline: 'Übergangszeitachse', checklist: 'Validierungscheckliste', findings: 'Hinweise', assumptions: 'Annahmen und Grenzen', sources: 'Maßgebliche Quellen', minute: 'Min.' },
} as const;

export function FailoverTool({ locale }: ToolPanelProps) {
  const [input, setInput] = useState(defaults);
  const c = copy[locale];
  const result = useMemo(() => analyzeWindowsFailover(input), [input]);
  const set = <K extends keyof WindowsFailoverInput>(key: K, value: WindowsFailoverInput[K]) => setInput((current) => ({ ...current, [key]: value }));
  const numericError = (field: keyof WindowsFailoverInput) => { const invalid = result.findings.find((finding) => finding.id === 'failover-invalid-numeric-input' && finding.evidence.some((item) => item.startsWith(`${field}=`))); if (invalid) return findingText(invalid, locale); const related: Partial<Record<keyof WindowsFailoverInput, WindowsFailoverFindingId[]>> = { mcltMinutes: ['failover-mclt-not-positive'], stateSwitchoverMinutes: ['failover-state-switchover-below-mclt'], clockSkewSeconds: ['failover-clock-skew-over-60-seconds'], loadBalancePercentage: ['failover-invalid-load-balance-percentage'], reservePercentage: ['failover-invalid-reserve-percentage'], plannedOutageMinutes: ['failover-outage-exceeds-safe-window'] }; const finding = result.findings.find((item) => related[field]?.includes(item.id)); return finding ? findingText(finding, locale) : ''; };
  const report = () => buildWorkbenchReport({ toolId: 'failover', toolName: locale === 'de' ? 'Failover-Design' : 'Failover design', generatedAt: new Date().toISOString(), locale, inputs: failoverReportInputs(input, locale), findings: result.findings.map((finding) => ({ severity: finding.severity, title: findingText(finding, locale), detail: finding.evidence.join('; ') })), assumptions: [locale === 'de' ? 'Das Modell bewertet Windows-DHCP-Failover für IPv4.' : 'The model assesses Windows DHCP failover for IPv4.'], sources: [{ label: 'Microsoft DHCP failover', url: 'https://learn.microsoft.com/en-us/windows-server/networking/technologies/dhcp/dhcp-failover' }], sensitiveValues: [] });
  return <div className="workbench-grid" data-testid="tool-panel-failover"><section className="planner-card workbench-form" aria-labelledby="failover-title"><h2 id="failover-title">{c.title}</h2><div className="workbench-fields"><label className="workbench-field"><span>{c.mode}</span><select value={input.mode} onChange={(event) => set('mode', event.target.value as WindowsFailoverInput['mode'])}><option value="load-balance">{c.load}</option><option value="hot-standby">{c.standby}</option></select></label><label className="workbench-field"><span>{c.protocol}</span><select value={input.scopeProtocol} onChange={(event) => set('scopeProtocol', event.target.value as WindowsFailoverInput['scopeProtocol'])}><option value="dhcpv4">DHCPv4</option><option value="dhcpv6">DHCPv6</option></select></label><Number label={c.mclt} value={input.mcltMinutes} onChange={(value) => set('mcltMinutes', value)} error={numericError('mcltMinutes')} /><Number label={c.switchover} value={input.stateSwitchoverMinutes} onChange={(value) => set('stateSwitchoverMinutes', value)} error={numericError('stateSwitchoverMinutes')} /><Number label={c.skew} value={input.clockSkewSeconds} onChange={(value) => set('clockSkewSeconds', value)} error={numericError('clockSkewSeconds')} /><Number label={c.outage} value={input.plannedOutageMinutes} onChange={(value) => set('plannedOutageMinutes', value)} error={numericError('plannedOutageMinutes')} /><Number label={c.loadPercent} value={input.loadBalancePercentage} onChange={(value) => set('loadBalancePercentage', value)} error={numericError('loadBalancePercentage')} /><Number label={c.reserve} value={input.reservePercentage} onChange={(value) => set('reservePercentage', value)} error={numericError('reservePercentage')} /></div>{([['partnerReachable', c.partner], ['clientsReachBothPartners', c.clients], ['tcp647Allowed', c.port], ['sameDnsUpdateCredentials', c.dns], ['configurationReplicated', c.replication], ['duplicateRelayForwarding', c.relay]] as const).map(([key, label]) => <label className="check-row" key={key}><input type="checkbox" checked={input[key]} onChange={(event) => set(key, event.target.checked)} />{label}</label>)}<div className="workbench-actions"><button type="button" className="secondary-button" onClick={() => setInput(defaults)}>{c.reset}</button><ReportDownloadActions createReport={report} filename="dhcpulse-failover-report" locale={locale} /></div></section>
    <section className="planner-card workbench-results" role="region" aria-labelledby="failover-result"><div className={`readiness readiness-${result.readiness}`}><span>{c.result}</span><h2 id="failover-result">{readiness(result.readiness, locale)}</h2></div><section className="workbench-section"><h3>{c.findings}</h3><ul className="finding-list-compact">{result.findings.map((finding) => <li key={finding.id} className={`finding-${finding.severity}`}><span className="severity">{severity(finding.severity, locale)}</span><div><strong>{findingText(finding, locale)}</strong><p>{finding.evidence.join('; ')}</p></div></li>)}</ul></section><section className="workbench-section"><h3>{c.timeline}</h3><ol className="timeline-compact">{result.timeline.map((step) => <li key={step.state}><strong>{step.afterMinutes} {c.minute} - {timelineState(step.state, locale)}</strong><span>{timelineText(step.state, locale)}</span></li>)}</ol></section><section className="workbench-section"><h3>{c.checklist}</h3><ul>{result.validationChecklist.map((item) => <li key={item.key}>{item.passed ? '✓' : '✕'} {checkText(item, locale)}</li>)}</ul></section><details className="workbench-section"><summary>{c.assumptions}</summary><p>{locale === 'de' ? 'Erreichbarkeit und Replikation müssen in der Zielumgebung separat geprüft werden.' : 'Reachability and replication must be validated separately in the target environment.'}</p></details><section className="workbench-section"><h3>{c.sources}</h3><a href="https://learn.microsoft.com/en-us/windows-server/networking/technologies/dhcp/dhcp-failover" target="_blank" rel="noreferrer">Microsoft DHCP failover</a></section></section></div>;
}

function Number({ label, value, onChange, error }: { label: string; value: number; onChange: (value: number) => void; error: string }) { const id = `failover-${label.replace(/\W/g, '-')}`; return <label className="workbench-field" htmlFor={id}><span>{label}</span><input id={id} type="number" min="0" value={globalThis.Number.isFinite(value) ? value : ''} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} onChange={(event) => onChange(event.target.value === '' ? globalThis.Number.NaN : event.target.valueAsNumber)} />{error && <small id={`${id}-error`} className="field-error">{error}</small>}</label>; }
function failoverReportInputs(input: WindowsFailoverInput, locale: 'en' | 'de') { const label = (de: string, en: string) => locale === 'de' ? de : en; return { [label('Hot-Standby', 'Hot standby')]: input.mode === 'hot-standby', [label('DHCPv6-Scope', 'DHCPv6 scope')]: input.scopeProtocol === 'dhcpv6', MCLT: input.mcltMinutes, [label('Statuswechsel', 'State switchover')]: input.stateSwitchoverMinutes, [label('Partner erreichbar', 'Partner reachable')]: input.partnerReachable, [label('Clients erreichen beide Partner', 'Clients reach both partners')]: input.clientsReachBothPartners, [label('TCP 647 erlaubt', 'TCP 647 allowed')]: input.tcp647Allowed, [label('Zeitabweichung', 'Clock skew')]: input.clockSkewSeconds, [label('DNS-Anmeldedaten stimmen überein', 'DNS credentials match')]: input.sameDnsUpdateCredentials, [label('Konfiguration repliziert', 'Configuration replicated')]: input.configurationReplicated, [label('Doppelte Relay-Weiterleitung', 'Duplicate relay forwarding')]: input.duplicateRelayForwarding, [label('Lastverteilung in Prozent', 'Load balance percentage')]: input.loadBalancePercentage, [label('Reserve in Prozent', 'Reserve percentage')]: input.reservePercentage, [label('Geplanter Ausfall', 'Planned outage')]: input.plannedOutageMinutes }; }
function readiness(value: string, locale: 'en' | 'de') { return locale === 'de' ? ({ ready: 'Bereit', caution: 'Mit Vorsicht', 'no-go': 'Nicht freigeben' } as Record<string, string>)[value] : ({ ready: 'Ready', caution: 'Caution', 'no-go': 'No-go' } as Record<string, string>)[value]; }
const findingDe: Record<WindowsFailoverFindingId, string> = { 'failover-invalid-numeric-input': 'Failover-Zeitwerte müssen nichtnegative sichere Ganzzahlen sein; Prozentwerte müssen zwischen 0 und 100 liegen.', 'failover-partner-unreachable': 'Der Replikationspfad zwischen den Failover-Partnern muss erreichbar sein.', 'failover-tcp-647-blocked': 'Windows-DHCP-Failover überträgt Partnerstatus über TCP 647.', 'failover-client-reachability-missing': 'Clients oder Relays müssen beide Partner erreichen können.', 'failover-clock-skew-over-60-seconds': 'Eine Zeitabweichung über 60 Sekunden macht Failover-Zeitannahmen ungültig.', 'windows-failover-dhcpv6-unsupported': 'Windows-DHCP-Failover schützt keine DHCPv6-Scopes.', 'failover-dns-credentials-mismatch': 'Beide Partner sollten dieselben DNS-Update-Anmeldedaten verwenden.', 'failover-configuration-not-replicated': 'Nicht alle Scope-Einstellungen werden automatisch repliziert.', 'failover-mclt-not-positive': 'MCLT muss größer als null sein.', 'failover-state-switchover-below-mclt': 'Der Statuswechsel darf nicht unter MCLT liegen.', 'failover-invalid-load-balance-percentage': 'Der Lastverteilungsanteil muss zwischen 0 und 100 liegen.', 'failover-invalid-reserve-percentage': 'Der Reserveanteil muss zwischen 0 und 100 liegen.', 'failover-duplicate-relay-forwarding': 'Doppelte Relay-Weiterleitung kann mehrere Antworten erzeugen.', 'failover-outage-exceeds-safe-window': 'Der geplante Ausfall überschreitet das modellierte sichere Zeitfenster.', 'windows-failover-ipv4-only': 'Windows-DHCP-Failover gilt nur für IPv4-Scopes.' };
function findingText(finding: WindowsFailoverFinding, locale: 'en' | 'de') { return locale === 'de' ? findingDe[finding.id] : finding.rationale; }
function severity(value: WindowsFailoverFinding['severity'], locale: 'en' | 'de') { const labels = locale === 'de' ? { blocker: 'Blocker', warning: 'Warnung', info: 'Hinweis' } : { blocker: 'Blocker', warning: 'Warning', info: 'Info' }; return labels[value]; }
function timelineState(value: string, locale: 'en' | 'de') { if (locale === 'en') return value; const labels: Record<string, string> = { normal: 'Normalbetrieb', 'communication-interrupted': 'Kommunikation unterbrochen', 'partner-down': 'Partner ausgefallen', 'mclt-full-pool-eligible': 'Gesamter Pool nach MCLT verfügbar' }; return labels[value] ?? 'Failover-Übergang'; }
function timelineText(value: string, locale: 'en' | 'de') { if (locale === 'en') return ({ normal: 'Both partners coordinate lease ownership.', 'communication-interrupted': 'Each partner initially protects the other partner’s lease ownership.', 'partner-down': 'The surviving partner can expand service after the configured transition.', 'mclt-full-pool-eligible': 'The surviving partner can become eligible for the complete address pool.' } as Record<string, string>)[value] ?? 'Review the transition.'; return ({ normal: 'Beide Partner koordinieren das Lease-Eigentum.', 'communication-interrupted': 'Jeder Partner schützt zunächst den Lease-Stand des anderen.', 'partner-down': 'Der verbleibende Partner kann den Dienst nach dem konfigurierten Übergang erweitern.', 'mclt-full-pool-eligible': 'Der verbleibende Partner kann den vollständigen Adresspool verwenden.' } as Record<string, string>)[value] ?? 'Übergang prüfen.'; }
function checkText(item: ValidationChecklistItem, locale: 'en' | 'de') { if (locale === 'en') return item.rationale; const labels: Record<string, string> = { 'numeric-inputs': 'Zeitwerte und Prozentangaben sind gültig.', 'partner-path': 'Der Partner-Replikationspfad ist erreichbar.', 'tcp-647': 'TCP 647 ist zwischen den Partnern erlaubt.', 'client-paths': 'Clients oder Relays erreichen beide Partner.', 'clock-skew': 'Die Zeitabweichung beträgt höchstens 60 Sekunden.', 'dns-credentials': 'DNS-Update-Anmeldedaten stimmen überein.', configuration: 'Die Scope-Konfiguration ist repliziert.', 'relay-forwarding': 'Relay-Weiterleitung ist nicht doppelt konfiguriert.', mclt: 'MCLT ist positiv.', 'state-switchover': 'Der Statuswechsel liegt nicht unter MCLT.', 'planned-outage': 'Der geplante Ausfall bleibt im modellierten Zeitfenster.', 'dhcpv4-scope': 'Der Scope verwendet DHCPv4.' }; return labels[item.key] ?? 'Prüfpunkt anhand der Herstellerdokumentation validieren.'; }
