import { useMemo, useState } from 'react';
import { analyzeWindowsFailover } from '../domain/failover';
import type { WindowsFailoverInput } from '../domain/types';
import { buildWorkbenchReport, downloadWorkbenchReport } from '../domain/workbench-export';
import type { ToolPanelProps } from './ToolPanel';

const defaults: WindowsFailoverInput = { mode: 'load-balance', mcltMinutes: 60, stateSwitchoverMinutes: 90, partnerReachable: true, clientsReachBothPartners: true, tcp647Allowed: true, clockSkewSeconds: 10, sameDnsUpdateCredentials: true, configurationReplicated: true, duplicateRelayForwarding: false, scopeProtocol: 'dhcpv4', loadBalancePercentage: 50, reservePercentage: 5, plannedOutageMinutes: 120 };
const labels = { en: { title: 'Windows DHCP failover readiness', mode: 'Failover mode', mclt: 'MCLT (minutes)', switchover: 'State switchover (minutes)', skew: 'Clock skew (seconds)', outage: 'Planned outage (minutes)', partner: 'Partner is reachable', clients: 'Clients can reach both partners', port: 'TCP port 647 allowed between partners', dns: 'DNS update credentials match', replication: 'Configuration is replicated', relay: 'Relay forwards duplicate requests', reset: 'Reset', download: 'Download report', result: 'Readiness result', timeline: 'Transition timeline', checklist: 'Validation checklist', findings: 'Findings', assumptions: 'Assumptions and limitations', sources: 'Authoritative sources' }, de: { title: 'Bereitschaft für Windows-DHCP-Failover', mode: 'Failover-Modus', mclt: 'MCLT (Minuten)', switchover: 'Statuswechsel (Minuten)', skew: 'Zeitabweichung (Sekunden)', outage: 'Geplanter Ausfall (Minuten)', partner: 'Partner ist erreichbar', clients: 'Clients erreichen beide Partner', port: 'TCP-Port 647 zwischen Partnern erlaubt', dns: 'DNS-Update-Anmeldedaten stimmen überein', replication: 'Konfiguration ist repliziert', relay: 'Relay leitet Anfragen doppelt weiter', reset: 'Zurücksetzen', download: 'Bericht herunterladen', result: 'Bereitschaftsergebnis', timeline: 'Übergangszeitachse', checklist: 'Validierungscheckliste', findings: 'Hinweise', assumptions: 'Annahmen und Grenzen', sources: 'Maßgebliche Quellen' } };

export function FailoverTool({ locale }: ToolPanelProps) {
  const [input, setInput] = useState(defaults); const c = labels[locale]; const result = useMemo(() => analyzeWindowsFailover(input), [input]);
  const set = <K extends keyof WindowsFailoverInput>(key: K, value: WindowsFailoverInput[K]) => setInput((current) => ({ ...current, [key]: value }));
  const download = () => { const report = buildWorkbenchReport({ toolId: 'failover', toolName: locale === 'de' ? 'Failover-Design' : 'Failover design', generatedAt: new Date().toISOString(), inputs: input as unknown as Record<string, unknown>, findings: result.findings.map((finding) => ({ severity: finding.severity, title: finding.rationale, detail: finding.evidence.join('; ') })), assumptions: [locale === 'de' ? 'Das Modell bewertet Windows-DHCP-Failover für IPv4.' : 'The model assesses Windows DHCP failover for IPv4.'], sources: [{ label: 'Microsoft DHCP failover', url: 'https://learn.microsoft.com/en-us/windows-server/networking/technologies/dhcp/dhcp-failover' }] }); downloadWorkbenchReport(report.markdown, 'dhcpulse-failover-report.md'); };
  return <div className="workbench-grid" data-testid="tool-panel-failover"><section className="planner-card workbench-form" aria-labelledby="failover-title"><h2 id="failover-title">{c.title}</h2><div className="workbench-fields"><label className="workbench-field"><span>{c.mode}</span><select value={input.mode} onChange={(event) => set('mode', event.target.value as WindowsFailoverInput['mode'])}><option value="load-balance">Load balance</option><option value="hot-standby">Hot standby</option></select></label><label className="workbench-field"><span>Scope protocol</span><select value={input.scopeProtocol} onChange={(event) => set('scopeProtocol', event.target.value as WindowsFailoverInput['scopeProtocol'])}><option value="dhcpv4">DHCPv4</option><option value="dhcpv6">DHCPv6</option></select></label><Number label={c.mclt} value={input.mcltMinutes} onChange={(value) => set('mcltMinutes', value)} /><Number label={c.switchover} value={input.stateSwitchoverMinutes} onChange={(value) => set('stateSwitchoverMinutes', value)} /><Number label={c.skew} value={input.clockSkewSeconds} onChange={(value) => set('clockSkewSeconds', value)} /><Number label={c.outage} value={input.plannedOutageMinutes} onChange={(value) => set('plannedOutageMinutes', value)} /><Number label="Load-balance percentage" value={input.loadBalancePercentage} onChange={(value) => set('loadBalancePercentage', value)} /><Number label="Hot-standby reserve percentage" value={input.reservePercentage} onChange={(value) => set('reservePercentage', value)} /></div>{([['partnerReachable',c.partner],['clientsReachBothPartners',c.clients],['tcp647Allowed',c.port],['sameDnsUpdateCredentials',c.dns],['configurationReplicated',c.replication],['duplicateRelayForwarding',c.relay]] as const).map(([key,label]) => <label className="check-row" key={key}><input type="checkbox" checked={input[key]} onChange={(event) => set(key, event.target.checked)} />{label}</label>)}<div className="workbench-actions"><button type="button" className="secondary-button" onClick={() => setInput(defaults)}>{c.reset}</button><button type="button" className="primary-button" onClick={download}>{c.download}</button></div></section>
    <section className="planner-card workbench-results" role="region" aria-labelledby="failover-result"><div className={`readiness readiness-${result.readiness}`}><span>{c.result}</span><h2 id="failover-result">{readiness(result.readiness, locale)}</h2></div><section className="workbench-section"><h3>{c.findings}</h3><ul className="finding-list-compact">{result.findings.map((finding) => <li key={finding.id} className={`finding-${finding.severity}`}><span className="severity">{finding.severity}</span><div><strong>{finding.rationale}</strong><p>{finding.evidence.join('; ')}</p></div></li>)}</ul></section><section className="workbench-section"><h3>{c.timeline}</h3><ol className="timeline-compact">{result.timeline.map((step) => <li key={step.state}><strong>{step.afterMinutes} min - {step.state}</strong><span>{step.rationale}</span></li>)}</ol></section><section className="workbench-section"><h3>{c.checklist}</h3><ul>{result.validationChecklist.map((item) => <li key={item.key}>{item.passed ? '✓' : '✕'} {item.rationale}</li>)}</ul></section><details className="workbench-section"><summary>{c.assumptions}</summary><p>{locale === 'de' ? 'Erreichbarkeit und Replikation müssen in der Zielumgebung separat geprüft werden.' : 'Reachability and replication must be validated separately in the target environment.'}</p></details><section className="workbench-section"><h3>{c.sources}</h3><a href="https://learn.microsoft.com/en-us/windows-server/networking/technologies/dhcp/dhcp-failover" target="_blank" rel="noreferrer">Microsoft DHCP failover</a></section></section></div>;
}
function Number({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="workbench-field"><span>{label}</span><input type="number" min="0" value={value} onChange={(event) => onChange(event.target.valueAsNumber || 0)} /></label>; }
function readiness(value: string, locale: 'en'|'de') { return locale === 'de' ? ({ ready: 'Bereit', caution: 'Mit Vorsicht', 'no-go': 'Nicht freigeben' } as Record<string,string>)[value] : ({ ready: 'Ready', caution: 'Caution', 'no-go': 'No-go' } as Record<string,string>)[value]; }
