import { useMemo, useState } from 'react';
import { decodeDhcpOption, encodeDhcpOption, searchDhcpOptions, validateDhcpOptions } from '../domain/dhcp-options';
import type { DhcpOptionDefinition, DhcpOptionEntry, DhcpOptionValidationIssue, DhcpOptionValueType, DhcpProtocol } from '../domain/types';
import { buildWorkbenchReport } from '../domain/workbench-export';
import { ReportDownloadActions } from './ReportDownloadActions';
import type { ToolPanelProps } from './ToolPanel';

interface EditableOption { id: number; protocol: DhcpProtocol; code: number; rawValue: string; }
const defaultEntries: EditableOption[] = [
  { id: 1, protocol: 'dhcpv4', code: 51, rawValue: '86400' },
  { id: 2, protocol: 'dhcpv4', code: 58, rawValue: '43200' },
  { id: 3, protocol: 'dhcpv4', code: 59, rawValue: '75600' },
];
const copy = {
  en: { title: 'Option registry and codec', search: 'Search option registry', protocol: 'Protocol filter', all: 'All protocols', encode: 'Encode typed value', decode: 'Decode hexadecimal', code: 'Option code', value: 'Typed value', hex: 'Hexadecimal value', type: 'Value type', output: 'Normalized output', editable: 'Editable option set', add: 'Add option', remove: 'Remove', validation: 'Validation findings', reset: 'Reset', download: 'Download report', assumptions: 'Assumptions and limitations', sources: 'Authoritative sources', empty: 'No validation findings.', mode: 'Codec mode' },
  de: { title: 'Optionsregister und Codec', search: 'Optionsregister durchsuchen', protocol: 'Protokollfilter', all: 'Alle Protokolle', encode: 'Typisierten Wert codieren', decode: 'Hexadezimalwert decodieren', code: 'Optionscode', value: 'Typisierter Wert', hex: 'Hexadezimalwert', type: 'Werttyp', output: 'Normalisierte Ausgabe', editable: 'Bearbeitbarer Optionssatz', add: 'Option hinzufügen', remove: 'Entfernen', validation: 'Validierungshinweise', reset: 'Zurücksetzen', download: 'Bericht herunterladen', assumptions: 'Annahmen und Grenzen', sources: 'Maßgebliche Quellen', empty: 'Keine Validierungshinweise.', mode: 'Codec-Modus' },
} as const;

export function OptionsTool({ locale }: ToolPanelProps) {
  const c = copy[locale];
  const [query, setQuery] = useState('domain search');
  const [filter, setFilter] = useState<'all' | DhcpProtocol>('dhcpv4');
  const [protocol, setProtocol] = useState<DhcpProtocol>('dhcpv4');
  const [mode, setMode] = useState<'encode' | 'decode'>('encode');
  const [code, setCode] = useState(119);
  const [value, setValue] = useState('example.com, lab.example.com');
  const [hex, setHex] = useState('076578616d706c6503636f6d00036c6162076578616d706c6503636f6d00');
  const [entries, setEntries] = useState<EditableOption[]>(defaultEntries);
  const registry = useMemo(() => searchDhcpOptions(query, filter === 'all' ? undefined : filter), [query, filter]);
  const definition = useMemo(() => definitionFor(protocol, code), [protocol, code]);
  const calculation = useMemo(() => {
    try {
      return mode === 'encode'
        ? { result: encodeDhcpOption({ protocol, code, value: coerceValue(definition?.valueType ?? 'hex', value) }), error: '' }
        : { result: decodeDhcpOption({ protocol, code, hex }), error: '' };
    } catch (error) { return { result: null, error: error instanceof Error ? error.message : String(error) }; }
  }, [code, definition, hex, mode, protocol, value]);
  const optionEntries = useMemo<DhcpOptionEntry[]>(() => entries.map((entry) => ({ protocol: entry.protocol, code: entry.code, value: coerceSafely(definitionFor(entry.protocol, entry.code)?.valueType ?? 'hex', entry.rawValue) })), [entries]);
  const issues = useMemo(() => validateDhcpOptions(optionEntries), [optionEntries]);
  const reset = () => { setQuery('domain search'); setFilter('dhcpv4'); setProtocol('dhcpv4'); setMode('encode'); setCode(119); setValue('example.com, lab.example.com'); setHex('076578616d706c6503636f6d00036c6162076578616d706c6503636f6d00'); setEntries(defaultEntries); };
  const findings = [...issues.map((issue) => ({ severity: issue.severity === 'error' ? 'blocker' as const : issue.severity, title: issueText(issue, locale) })), ...(calculation.error ? [{ severity: 'blocker' as const, title: codecText(calculation.error, locale) }] : [])];
  const report = () => buildWorkbenchReport({ toolId: 'options', toolName: locale === 'de' ? 'DHCP-Optionen' : 'DHCP options', generatedAt: new Date().toISOString(), locale, inputs: { [locale === 'de' ? 'Optionscode' : 'Option code']: code, [locale === 'de' ? 'DHCPv6 ausgewählt' : 'DHCPv6 selected']: protocol === 'dhcpv6', [locale === 'de' ? 'Decodiermodus' : 'Decode mode']: mode === 'decode', [locale === 'de' ? 'Bearbeitbare Optionen' : 'Editable options']: entries.length }, findings, assumptions: [locale === 'de' ? 'Die Codierung folgt dem im lokalen Register definierten Werttyp.' : 'Encoding follows the value type in the local registry.'], sources: [{ label: 'IANA DHCP Parameters', url: 'https://www.iana.org/assignments/bootp-dhcp-parameters/' }, { label: 'RFC 3397', url: 'https://www.rfc-editor.org/rfc/rfc3397.html' }, { label: 'RFC 3442', url: 'https://www.rfc-editor.org/rfc/rfc3442.html' }], sensitiveValues: [query, value, hex, ...entries.map((entry) => entry.rawValue)] });
  const updateEntry = (id: number, patch: Partial<EditableOption>) => setEntries((current) => current.map((entry) => entry.id === id ? { ...entry, ...patch } : entry));
  return <div className="workbench-grid" data-testid="tool-panel-options"><section className="planner-card workbench-form" aria-labelledby="options-title"><h2 id="options-title">{c.title}</h2>
    <div className="workbench-actions preset-actions"><button type="button" className="secondary-button" onClick={() => { setProtocol('dhcpv4'); setCode(119); setMode('encode'); setValue('example.com, lab.example.com'); }}>{locale === 'de' ? 'Domänensuchlisten-Beispiel' : 'Domain-search example'}</button><button type="button" className="secondary-button" onClick={() => { setProtocol('dhcpv4'); setCode(121); setMode('encode'); setValue('0.0.0.0/0 via 192.0.2.1; 10.20.99.1/16 via 192.0.2.254'); }}>{locale === 'de' ? 'Beispiel für klassenlose Routen' : 'Classless-route example'}</button></div>
    <div className="workbench-fields"><label className="workbench-field span-2"><span>{c.search}</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} /></label><label className="workbench-field"><span>{c.protocol}</span><select value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)}><option value="all">{c.all}</option><option value="dhcpv4">DHCPv4</option><option value="dhcpv6">DHCPv6</option></select></label></div>
    <ul className="registry-list" aria-label={c.search}>{registry.slice(0, 8).map((option) => <li key={`${option.protocol}-${option.code}`}><button type="button" onClick={() => { setProtocol(option.protocol); setCode(option.code); }}><strong>{option.code} - {locale === 'de' ? `${option.protocol.toUpperCase()}-Option ${option.code}` : option.name}</strong><span>{option.valueType} · {option.source}</span></button></li>)}</ul>
    <fieldset className="mode-switch"><legend className="visually-hidden">{c.mode}</legend><label><input type="radio" name="codec-mode" checked={mode === 'encode'} onChange={() => setMode('encode')} />{c.encode}</label><label><input type="radio" name="codec-mode" checked={mode === 'decode'} onChange={() => setMode('decode')} />{c.decode}</label></fieldset>
    <div className="workbench-fields"><label className="workbench-field"><span>{c.code}</span><input type="number" min="0" max="65535" value={Number.isFinite(code) ? code : ''} onChange={(event) => setCode(event.target.valueAsNumber)} /></label><label className="workbench-field"><span>{c.protocol}</span><select value={protocol} onChange={(event) => setProtocol(event.target.value as DhcpProtocol)}><option value="dhcpv4">DHCPv4</option><option value="dhcpv6">DHCPv6</option></select></label>{mode === 'encode' ? <CodecValue label={c.value} type={definition?.valueType ?? 'hex'} value={value} error={calculation.error ? codecText(calculation.error, locale) : ''} onChange={setValue} /> : <label className="workbench-field span-2"><span>{c.hex}</span><input value={hex} aria-invalid={Boolean(calculation.error)} aria-describedby={calculation.error ? 'option-codec-error' : undefined} onChange={(event) => setHex(event.target.value)} />{calculation.error && <small id="option-codec-error" className="field-error">{codecText(calculation.error, locale)}</small>}</label>}</div>
    <fieldset className="option-set"><legend>{c.editable}</legend>{entries.map((entry, index) => { const rowDefinition = definitionFor(entry.protocol, entry.code); const rowIssues = issues.filter((issue) => issue.protocol === entry.protocol && issue.code === entry.code); const error = rowIssues.map((issue) => issueText(issue, locale)).join(' '); return <div className="option-row" key={entry.id}><label className="workbench-field"><span>{`Option ${index + 1} ${locale === 'de' ? 'Protokoll' : 'protocol'}`}</span><select value={entry.protocol} onChange={(event) => updateEntry(entry.id, { protocol: event.target.value as DhcpProtocol })}><option value="dhcpv4">DHCPv4</option><option value="dhcpv6">DHCPv6</option></select></label><label className="workbench-field"><span>{`Option ${index + 1} ${locale === 'de' ? 'Code' : 'code'}`}</span><input type="number" min="0" max="65535" value={Number.isFinite(entry.code) ? entry.code : ''} aria-invalid={Boolean(error)} aria-describedby={error ? `option-row-${entry.id}-error` : undefined} onChange={(event) => updateEntry(entry.id, { code: event.target.valueAsNumber })} /></label><TypedInput label={`Option ${index + 1} ${locale === 'de' ? 'Wert' : 'value'}`} type={rowDefinition?.valueType ?? 'hex'} value={entry.rawValue} error={error} errorId={`option-row-${entry.id}-error`} onChange={(rawValue) => updateEntry(entry.id, { rawValue })} /><button type="button" className="text-button" disabled={entries.length === 1} onClick={() => setEntries((current) => current.filter((item) => item.id !== entry.id))}>{c.remove}</button></div>; })}<button type="button" className="secondary-button" onClick={() => setEntries((current) => [...current, { id: Math.max(0, ...current.map((entry) => entry.id)) + 1, protocol: 'dhcpv4', code: 6, rawValue: '192.0.2.53' }])}>{c.add}</button></fieldset>
    <div className="workbench-actions"><button type="button" className="secondary-button" onClick={reset}>{c.reset}</button><ReportDownloadActions createReport={report} filename="dhcpulse-options-report" locale={locale} /></div></section>
    <section className="planner-card workbench-results" role="region" aria-labelledby="option-output"><h2 id="option-output">{c.output}</h2>{calculation.result && <><dl className="fact-grid"><div><dt>{c.type}</dt><dd>{calculation.result.definition?.valueType ?? 'hex'}</dd></div><div><dt>Hex</dt><dd className="mono-break">{calculation.result.hex}</dd></div>{'displayValue' in calculation.result && <div><dt>{c.value}</dt><dd>{String(calculation.result.displayValue)}</dd></div>}</dl>{calculation.result.warnings.map((warning) => <p key={warning} className="field-help">{codecText(warning, locale)}</p>)}</>}
      <section className="workbench-section"><h3>{c.validation}</h3>{issues.length ? <ul className="finding-list-compact">{issues.map((issue, index) => <li key={`${issue.key}-${issue.code}-${index}`} className={`finding-${issue.severity}`}><span className="severity">{severity(issue.severity, locale)}</span>{issueText(issue, locale)}</li>)}</ul> : <p>{c.empty}</p>}</section><details className="workbench-section"><summary>{c.assumptions}</summary><p>{locale === 'de' ? 'Die Codierung folgt dem lokal registrierten Typ. Herstelleroptionen benötigen eine zusätzliche Prüfung.' : 'Encoding follows the locally registered type. Vendor options require additional review.'}</p></details><section className="workbench-section"><h3>{c.sources}</h3><a href="https://www.iana.org/assignments/bootp-dhcp-parameters/" target="_blank" rel="noreferrer">IANA DHCP Parameters</a></section></section></div>;
}

function definitionFor(protocol: DhcpProtocol, code: number): DhcpOptionDefinition | undefined { return searchDhcpOptions('', protocol).find((item) => item.code === code); }
function coerceValue(type: DhcpOptionValueType, raw: string): unknown { if (['uint8', 'uint16', 'uint32'].includes(type)) return Number(raw); if (type === 'boolean') return raw === 'true'; if (type === 'message-type' && /^\d+$/.test(raw.trim())) return Number(raw); return raw; }
function coerceSafely(type: DhcpOptionValueType, raw: string): unknown { try { return coerceValue(type, raw); } catch { return raw; } }
function TypedInput({ label, type, value, error, errorId, onChange }: { label: string; type: DhcpOptionValueType; value: string; error: string; errorId: string; onChange: (value: string) => void }) { if (type === 'boolean') return <label className="workbench-field"><span>{label}</span><select value={value} aria-invalid={Boolean(error)} aria-describedby={error ? errorId : undefined} onChange={(event) => onChange(event.target.value)}><option value="true">true</option><option value="false">false</option></select>{error && <small id={errorId} className="field-error">{error}</small>}</label>; const numeric = ['uint8', 'uint16', 'uint32'].includes(type); return <label className="workbench-field"><span>{label}</span><input type={numeric ? 'number' : 'text'} value={value} aria-invalid={Boolean(error)} aria-describedby={error ? errorId : undefined} onChange={(event) => onChange(event.target.value)} />{error && <small id={errorId} className="field-error">{error}</small>}</label>; }
function CodecValue({ label, type, value, error, onChange }: { label: string; type: DhcpOptionValueType; value: string; error: string; onChange: (value: string) => void }) { return <div className="span-2"><TypedInput label={label} type={type} value={value} error={error} errorId="option-codec-error" onChange={onChange} /></div>; }
function issueText(issue: DhcpOptionValidationIssue, locale: 'en' | 'de') { if (locale === 'en') return issue.message; const messages: Record<DhcpOptionValidationIssue['key'], string> = { duplicateSingleton: `Option ${issue.code} darf nicht mehrfach vorkommen.`, invalidValue: `Option ${issue.code} hat einen ungültigen Wert.`, t1NotBeforeT2: 'T1 muss kleiner als T2 sein.', t2NotBeforeLease: 'T2 muss kleiner als die Lease-Dauer sein.', pxeContextMissing: 'Option 66/67 zusammen mit der PXE-Umgebung prüfen.', classlessRouteWithoutRouter: 'Clients ohne Unterstützung für Option 121 benötigen möglicherweise Option 3 als Standardgateway.' }; return messages[issue.key]; }
function codecText(message: string, locale: 'en' | 'de') { if (locale === 'en') return message; if (message.includes('non-hexadecimal')) return 'Der Wert enthält Zeichen außerhalb des Hexadezimalsystems.'; if (message.includes('even number')) return 'Hexadezimaldaten müssen eine gerade Anzahl Ziffern enthalten.'; if (message.includes('unsigned')) return 'Der Wert muss eine vorzeichenlose Ganzzahl im zulässigen Bereich sein.'; if (message.includes('Invalid IPv4')) return 'Die IPv4-Adresse ist ungültig.'; if (message.startsWith('Unknown')) return 'Unbekannte Option; Codierung und Typ müssen geprüft werden.'; return 'Der Optionswert ist für den registrierten Werttyp ungültig.'; }
function severity(value: DhcpOptionValidationIssue['severity'], locale: 'en' | 'de') { const map = locale === 'de' ? { error: 'Fehler', warning: 'Warnung', info: 'Hinweis' } : { error: 'Error', warning: 'Warning', info: 'Info' }; return map[value]; }
