import { useMemo, useState } from 'react';
import { analyzePxe } from '../domain/pxe';
import type { PxeAnalysisInput, PxeArchitecture, PxeDeploymentMode, PxeFinding } from '../domain/types';
import { buildWorkbenchReport } from '../domain/workbench-export';
import { ReportDownloadActions } from './ReportDownloadActions';
import type { ToolPanelProps } from './ToolPanel';

const architectures: [PxeArchitecture, string][] = [['bios-x86', 'BIOS x86'], ['uefi-x86', 'UEFI x86'], ['uefi-x64', 'UEFI x64'], ['uefi-arm64', 'UEFI ARM64'], ['http-x64', 'HTTP Boot x64']];
const defaults: PxeAnalysisInput = { architecture: 'uefi-x64', architectures: ['uefi-x64'], vendorClass: 'PXEClient', userClass: 'iPXE', serverName: 'pxe.example.test', bootFile: 'bootx64.efi', proxyDhcp: false, authoritativeBootOptions: true, mode: 'none', ipxeChainload: false, userClassPolicy: true, globalBootFile: false };
const copy = {
  en: { title: 'PXE decision model', architecture: 'Client architectures', platform: 'Deployment platform', proxy: 'Use proxyDHCP', vendor: 'Vendor class', user: 'User class', server: 'Boot server', file: 'Boot file', global: 'Use one global boot file for mixed architectures', reset: 'Reset', download: 'Download report', summary: 'PXE result', code: 'Architecture codes', family: 'Recommended boot file families', findings: 'Findings', path: 'Decision path', snippets: 'Review-only snippets', assumptions: 'Assumptions and limitations', sources: 'Authoritative sources', none: 'No PXE conflicts detected.', standalone: 'Standalone', reviewOnly: 'REVIEW ONLY' },
  de: { title: 'PXE-Entscheidungsmodell', architecture: 'Client-Architekturen', platform: 'Bereitstellungsplattform', proxy: 'proxyDHCP verwenden', vendor: 'Herstellerklasse', user: 'Benutzerklasse', server: 'Bootserver', file: 'Bootdatei', global: 'Eine globale Bootdatei für gemischte Architekturen verwenden', reset: 'Zurücksetzen', download: 'Bericht herunterladen', summary: 'PXE-Ergebnis', code: 'Architekturcodes', family: 'Empfohlene Bootdateifamilien', findings: 'Hinweise', path: 'Entscheidungspfad', snippets: 'Nur zur Prüfung bestimmte Beispiele', assumptions: 'Annahmen und Grenzen', sources: 'Maßgebliche Quellen', none: 'Keine PXE-Konflikte erkannt.', standalone: 'Eigenständig', reviewOnly: 'NUR PRÜFEN' },
} as const;

export function PxeTool({ locale }: ToolPanelProps) {
  const [input, setInput] = useState<PxeAnalysisInput>(defaults);
  const c = copy[locale];
  const selected = useMemo(() => input.architectures?.length ? input.architectures : [input.architecture], [input.architecture, input.architectures]);
  const result = useMemo(() => analyzePxe({ ...input, architecture: selected[0]!, architectures: selected }), [input, selected]);
  const selectedResults = useMemo(() => selected.map((architecture) => analyzePxe({ ...input, architecture, architectures: [architecture] })), [input, selected]);
  const codes = [...new Set(selectedResults.flatMap((item) => item.architectureCodes))];
  const families = [...new Set(selectedResults.map((item) => item.recommendedBootFileFamily))];
  const set = <K extends keyof PxeAnalysisInput>(key: K, value: PxeAnalysisInput[K]) => setInput((current) => ({ ...current, [key]: value }));
  const setArchitecture = (architecture: PxeArchitecture, checked: boolean) => setInput((current) => { const currentArchitectures = current.architectures ?? [current.architecture]; const next = checked ? [...new Set([...currentArchitectures, architecture])] : currentArchitectures.filter((item) => item !== architecture); if (next.length === 0) return current; return { ...current, architecture: next[0]!, architectures: next }; });
  const find = (...keys: PxeFinding['key'][]) => result.findings.find((finding) => keys.includes(finding.key));
  const report = () => buildWorkbenchReport({ toolId: 'pxe', toolName: locale === 'de' ? 'PXE-Boot' : 'PXE boot', generatedAt: new Date().toISOString(), locale, inputs: { [locale === 'de' ? 'Architekturen' : 'Architectures']: selected.length, [locale === 'de' ? 'ProxyDHCP aktiv' : 'ProxyDHCP enabled']: Boolean(input.proxyDhcp), [locale === 'de' ? 'Globale Bootdatei' : 'Global boot file']: Boolean(input.globalBootFile), [locale === 'de' ? 'Bootserver angegeben' : 'Boot server provided']: Boolean(input.serverName || input.serverAddress), [locale === 'de' ? 'Bootdatei angegeben' : 'Boot file provided']: Boolean(input.bootFile) }, findings: result.findings.map((finding) => ({ severity: finding.severity, title: findingText(finding.key, locale) })), assumptions: [reviewNotice(locale)], sources: [{ label: 'RFC 4578', url: 'https://www.rfc-editor.org/rfc/rfc4578.html' }, { label: 'Microsoft PXE architecture guidance', url: 'https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/pxe-boot-guid-guid-format' }], sensitiveValues: [input.vendorClass ?? '', input.userClass ?? '', input.serverName ?? '', input.serverAddress ?? '', input.bootFile ?? ''] });
  return <div className="workbench-grid" data-testid="tool-panel-pxe"><section className="planner-card workbench-form" aria-labelledby="pxe-title"><h2 id="pxe-title">{c.title}</h2>
    <fieldset className="architecture-grid"><legend>{c.architecture}</legend>{architectures.map(([key, label]) => <label className="check-row" key={key}><input type="checkbox" checked={selected.includes(key)} onChange={(event) => setArchitecture(key, event.target.checked)} />{label}</label>)}</fieldset>
    <div className="workbench-fields"><Select label={c.platform} value={input.mode ?? 'none'} onChange={(value) => set('mode', value as PxeDeploymentMode)} options={[['none', c.standalone], ['wds', 'WDS'], ['mdt', 'MDT'], ['mecm', 'MECM']]} /><Text label={c.vendor} value={input.vendorClass ?? ''} onChange={(value) => set('vendorClass', value)} /><Text label={c.user} value={input.userClass ?? ''} onChange={(value) => set('userClass', value)} /><Text label={c.server} value={input.serverName ?? input.serverAddress ?? ''} onChange={(value) => set('serverName', value)} error={find('missingServer', 'option66Url') ? findingText(find('missingServer', 'option66Url')!.key, locale) : undefined} /><Text label={c.file} value={input.bootFile ?? ''} onChange={(value) => set('bootFile', value)} error={find('missingBootFile', 'httpBootRequiresUrl') ? findingText(find('missingBootFile', 'httpBootRequiresUrl')!.key, locale) : undefined} /></div>
    <Check label={c.proxy} checked={Boolean(input.proxyDhcp)} onChange={(checked) => set('proxyDhcp', checked)} error={find('proxyDhcpWithAuthoritativeOptions') ? findingText('proxyDhcpWithAuthoritativeOptions', locale) : undefined} />
    <Check label={c.global} checked={Boolean(input.globalBootFile)} onChange={(checked) => set('globalBootFile', checked)} error={find('globalBootFileMixedArchitectures') ? findingText('globalBootFileMixedArchitectures', locale) : undefined} />
    <div className="workbench-actions"><button type="button" className="secondary-button" onClick={() => setInput(defaults)}>{c.reset}</button><ReportDownloadActions createReport={report} filename="dhcpulse-pxe-report" locale={locale} /></div></section>
    <section className="planner-card workbench-results" role="region" aria-labelledby="pxe-result"><h2 id="pxe-result">{c.summary}</h2><dl className="fact-grid"><div><dt>{c.code}</dt><dd>{codes.join(', ')}</dd></div><div><dt>{c.family}</dt><dd>{families.join(', ')}</dd></div></dl><section className="workbench-section"><h3>{c.findings}</h3>{result.findings.length ? <ul className="finding-list-compact">{result.findings.map((finding) => <li key={finding.key} className={`finding-${finding.severity}`}><span className="severity">{locale === 'de' ? 'Warnung' : 'Warning'}</span>{findingText(finding.key, locale)}</li>)}</ul> : <p>{c.none}</p>}</section><section className="workbench-section"><h3>{c.path}</h3><ol>{result.decisionSteps.map((step) => <li key={step.key}>{decisionText(step.key, locale)}</li>)}</ol></section><section className="workbench-section"><h3>{c.snippets}</h3><p className="review-notice">{reviewNotice(locale)}</p><details><summary>Microsoft DHCP PowerShell - {c.reviewOnly}</summary><pre>{selectedResults.map((item) => item.policyExamples.microsoftDhcpPowerShell).join('\n\n')}</pre></details><details><summary>Kea JSON - {c.reviewOnly}</summary><pre>{selectedResults.map((item) => item.policyExamples.keaJson).join('\n\n')}</pre></details></section><details className="workbench-section"><summary>{c.assumptions}</summary><p>{reviewNotice(locale)}</p></details><section className="workbench-section"><h3>{c.sources}</h3><ul><li><a href="https://www.rfc-editor.org/rfc/rfc4578.html" target="_blank" rel="noreferrer">RFC 4578</a></li><li><a href="https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/pxe-boot-guid-guid-format" target="_blank" rel="noreferrer">Microsoft PXE architecture guidance</a></li></ul></section></section></div>;
}

function Text({ label, value, onChange, error }: { label: string; value: string; onChange: (value: string) => void; error?: string }) { const id = `pxe-${label.replace(/\W/g, '-')}`; return <label className="workbench-field" htmlFor={id}><span>{label}</span><input id={id} value={value} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} onChange={(event) => onChange(event.target.value)} />{error && <small id={`${id}-error`} className="field-error">{error}</small>}</label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: readonly (readonly [string, string])[] }) { return <label className="workbench-field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{options.map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label>; }
function Check({ label, checked, onChange, error }: { label: string; checked: boolean; onChange: (value: boolean) => void; error?: string }) { const id = `pxe-${label.replace(/\W/g, '-')}`; return <div><label className="check-row" htmlFor={id}><input id={id} type="checkbox" checked={checked} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} onChange={(event) => onChange(event.target.checked)} />{label}</label>{error && <small id={`${id}-error`} className="field-error">{error}</small>}</div>; }
function findingText(key: PxeFinding['key'], locale: 'en' | 'de') { const values: Record<PxeFinding['key'], [string, string]> = { globalBootFileMixedArchitectures: ['A single global boot file cannot safely represent mixed firmware architectures.', 'Eine einzelne globale Bootdatei kann gemischte Firmware-Architekturen nicht sicher abbilden.'], option66Url: ['Option 66 is a server name, not a URL; keep URL boot resources in the boot-file decision.', 'Option 66 enthält einen Servernamen, keine URL; URL-Bootressourcen gehören in die Bootdatei-Entscheidung.'], httpBootRequiresUrl: ['HTTP Boot requires an HTTP(S) boot-file URL.', 'HTTP Boot benötigt eine HTTP(S)-URL als Bootdatei.'], ipxeLoopRisk: ['Branch on the iPXE user class to avoid a chainload loop.', 'Nach der iPXE-Benutzerklasse verzweigen, um eine Chainload-Schleife zu vermeiden.'], proxyDhcpWithAuthoritativeOptions: ['ProxyDHCP and authoritative boot options can conflict; define which service owns each response.', 'ProxyDHCP und autoritative Bootoptionen können kollidieren; die Zuständigkeit für jede Antwort muss feststehen.'], missingServer: ['A boot server address or name is required for review.', 'Für die Prüfung ist eine Bootserver-Adresse oder ein Name erforderlich.'], missingBootFile: ['A boot file is required for review.', 'Für die Prüfung ist eine Bootdatei erforderlich.'], directOptionsWithManagedDeployment: ['Managed deployment commonly requires policies or ProxyDHCP instead of unconditional options 66/67.', 'Verwaltete Bereitstellung benötigt üblicherweise Richtlinien oder ProxyDHCP statt bedingungsloser Optionen 66/67.'] }; return values[key][locale === 'de' ? 1 : 0]; }
function decisionText(key: string, locale: 'en' | 'de') { const values: Record<string, [string, string]> = { identifyArchitecture: ['Identify client architecture codes and firmware transport.', 'Client-Architekturcodes und Firmware-Transport bestimmen.'], identifyResponder: ['Identify the authoritative DHCP and optional ProxyDHCP responders.', 'Autoritative DHCP- und optionale ProxyDHCP-Antwortdienste bestimmen.'], branchClasses: ['Branch on architecture, vendor class, and iPXE user class where applicable.', 'Nach Architektur, Herstellerklasse und gegebenenfalls iPXE-Benutzerklasse verzweigen.'], selectBootResource: ['Select a server and boot file appropriate to the matched architecture.', 'Server und Bootdatei passend zur erkannten Architektur auswählen.'], labValidate: ['Review and validate the policy in an isolated representative environment.', 'Richtlinie in einer isolierten, repräsentativen Umgebung prüfen und validieren.'] }; return values[key]?.[locale === 'de' ? 1 : 0] ?? (locale === 'de' ? 'Entscheidungsschritt prüfen.' : 'Review decision step.'); }
function reviewNotice(locale: 'en' | 'de') { return locale === 'de' ? 'Generierte Richtlinienbeispiele dienen nur zur Prüfung und müssen vor jeder Verwendung an die Umgebung angepasst werden.' : 'Generated policy examples are review-only and require environment review before any use.'; }
