import { useMemo, useState } from 'react';
import { analyzePxe } from '../domain/pxe';
import type { PxeAnalysisInput, PxeArchitecture, PxeDeploymentMode } from '../domain/types';
import { buildWorkbenchReport, downloadWorkbenchReport } from '../domain/workbench-export';
import type { ToolPanelProps } from './ToolPanel';

const defaults: PxeAnalysisInput = { architecture: 'uefi-x64', architectures: ['uefi-x64', 'bios-x86'], vendorClass: 'PXEClient', userClass: 'iPXE', serverName: 'pxe.example.test', bootFile: 'bootx64.efi', proxyDhcp: false, authoritativeBootOptions: true, mode: 'none', ipxeChainload: false, userClassPolicy: true, globalBootFile: false };
const copy = { en: { title: 'PXE decision model', architecture: 'Client architecture', platform: 'Deployment platform', proxy: 'Use proxyDHCP', vendor: 'Vendor class', user: 'User class', server: 'Boot server', file: 'Boot file', global: 'Use one global boot file for mixed architectures', reset: 'Reset', download: 'Download report', summary: 'PXE result', code: 'Architecture code', family: 'Recommended boot file family', findings: 'Findings', path: 'Decision path', snippets: 'Review-only snippets', assumptions: 'Assumptions and limitations', sources: 'Authoritative sources' }, de: { title: 'PXE-Entscheidungsmodell', architecture: 'Client-Architektur', platform: 'Bereitstellungsplattform', proxy: 'proxyDHCP verwenden', vendor: 'Vendor-Klasse', user: 'User-Klasse', server: 'Bootserver', file: 'Bootdatei', global: 'Eine globale Bootdatei für gemischte Architekturen verwenden', reset: 'Zurücksetzen', download: 'Bericht herunterladen', summary: 'PXE-Ergebnis', code: 'Architekturcode', family: 'Empfohlene Bootdateifamilie', findings: 'Hinweise', path: 'Entscheidungspfad', snippets: 'Nur zur Prüfung bestimmte Beispiele', assumptions: 'Annahmen und Grenzen', sources: 'Maßgebliche Quellen' } };

export function PxeTool({ locale }: ToolPanelProps) {
  const [input, setInput] = useState<PxeAnalysisInput>(defaults); const c = copy[locale];
  const result = useMemo(() => analyzePxe(input), [input]);
  const set = <K extends keyof PxeAnalysisInput>(key: K, value: PxeAnalysisInput[K]) => setInput((current) => ({ ...current, [key]: value }));
  const download = () => { const report = buildWorkbenchReport({ toolId: 'pxe', toolName: locale === 'de' ? 'PXE-Boot' : 'PXE boot', generatedAt: new Date().toISOString(), inputs: input as unknown as Record<string, unknown>, findings: result.findings.map((finding) => ({ severity: finding.severity, title: finding.message })), assumptions: [result.reviewNotice], sources: [{ label: 'RFC 4578', url: 'https://www.rfc-editor.org/rfc/rfc4578.html' }, { label: 'Microsoft PXE architecture', url: 'https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/pxe-boot-guid-guid-format' }] }); downloadWorkbenchReport(report.markdown, 'dhcpulse-pxe-report.md'); };
  return <div className="workbench-grid" data-testid="tool-panel-pxe"><section className="planner-card workbench-form" aria-labelledby="pxe-title"><h2 id="pxe-title">{c.title}</h2><div className="workbench-fields"><Select label={c.architecture} value={input.architecture} onChange={(value) => set('architecture', value as PxeArchitecture)} options={[['bios-x86','BIOS x86'],['uefi-x86','UEFI x86'],['uefi-x64','UEFI x64'],['uefi-arm64','UEFI ARM64'],['http-x64','HTTP Boot x64']]} /><Select label={c.platform} value={input.mode ?? 'none'} onChange={(value) => set('mode', value as PxeDeploymentMode)} options={[['none','Standalone'],['wds','WDS'],['mdt','MDT'],['mecm','MECM']]} /><Text label={c.vendor} value={input.vendorClass ?? ''} onChange={(value) => set('vendorClass', value)} /><Text label={c.user} value={input.userClass ?? ''} onChange={(value) => set('userClass', value)} /><Text label={c.server} value={input.serverName ?? input.serverAddress ?? ''} onChange={(value) => set('serverName', value)} /><Text label={c.file} value={input.bootFile ?? ''} onChange={(value) => set('bootFile', value)} /></div><label className="check-row"><input type="checkbox" checked={Boolean(input.proxyDhcp)} onChange={(event) => set('proxyDhcp', event.target.checked)} />{c.proxy}</label><label className="check-row"><input type="checkbox" checked={Boolean(input.globalBootFile)} onChange={(event) => set('globalBootFile', event.target.checked)} />{c.global}</label><div className="workbench-actions"><button type="button" className="secondary-button" onClick={() => setInput(defaults)}>{c.reset}</button><button type="button" className="primary-button" onClick={download}>{c.download}</button></div></section>
    <section className="planner-card workbench-results" role="region" aria-labelledby="pxe-result"><h2 id="pxe-result">{c.summary}</h2><dl className="fact-grid"><div><dt>{c.code}</dt><dd>{result.architectureCodes.join(', ')}</dd></div><div><dt>{c.family}</dt><dd>{result.recommendedBootFileFamily}</dd></div></dl><section className="workbench-section"><h3>{c.findings}</h3>{result.findings.length ? <ul className="finding-list-compact">{result.findings.map((finding) => <li key={finding.key} className={`finding-${finding.severity}`}><span className="severity">{finding.severity}</span>{finding.message}</li>)}</ul> : <p>{locale === 'de' ? 'Keine PXE-Konflikte erkannt.' : 'No PXE conflicts detected.'}</p>}</section><section className="workbench-section"><h3>{c.path}</h3><ol>{result.decisionSteps.map((step) => <li key={step.key}>{step.instruction}</li>)}</ol></section><section className="workbench-section"><h3>{c.snippets}</h3><p className="review-notice">{result.reviewNotice}</p><details><summary>Microsoft DHCP PowerShell - REVIEW ONLY</summary><pre>{result.policyExamples.microsoftDhcpPowerShell}</pre></details><details><summary>Kea JSON - REVIEW ONLY</summary><pre>{result.policyExamples.keaJson}</pre></details></section><details className="workbench-section"><summary>{c.assumptions}</summary><p>{result.reviewNotice}</p></details><section className="workbench-section"><h3>{c.sources}</h3><a href="https://www.rfc-editor.org/rfc/rfc4578.html" target="_blank" rel="noreferrer">RFC 4578</a></section></section></div>;
}
function Text({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="workbench-field"><span>{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: [string,string][] }) { return <label className="workbench-field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{options.map(([key,name]) => <option key={key} value={key}>{name}</option>)}</select></label>; }
