import { useMemo, useState } from 'react';
import { analyzeIpv4Cidr } from '../domain/ip-address';
import { analyzeScopeDesign } from '../domain/scope-design';
import { buildWorkbenchReport, downloadWorkbenchReport } from '../domain/workbench-export';
import type { ToolPanelProps } from './ToolPanel';

const defaults = { cidr: '192.0.2.0/24', gateway: '192.0.2.1', poolStart: '192.0.2.50', poolEnd: '192.0.2.200', exclusions: '192.0.2.100-192.0.2.104', reservations: '192.0.2.60', leases: 40, growth: 4 };
const copy = {
  en: { title: 'IPv4 scope model', cidr: 'CIDR', gateway: 'Gateway', start: 'Pool start', end: 'Pool end', exclusions: 'Exclusions (start-end, one per line)', reservations: 'Reservations (address, one per line)', leases: 'Current leases', growth: 'Expected daily growth', reset: 'Reset', download: 'Download report', summary: 'Capacity summary', usable: 'Usable addresses', remaining: 'addresses remain', runway: 'days of runway', findings: 'Findings', assumptions: 'Assumptions and limitations', sources: 'Authoritative sources', invalid: 'Enter a valid IPv4 CIDR.', none: 'No capacity or collision findings.', bar: 'Address-space utilization' },
  de: { title: 'IPv4-Scope-Modell', cidr: 'CIDR', gateway: 'Gateway', start: 'Pool-Start', end: 'Pool-Ende', exclusions: 'Ausschlüsse (Start-Ende, eine Zeile je Bereich)', reservations: 'Reservierungen (eine Adresse je Zeile)', leases: 'Aktuelle Leases', growth: 'Erwartetes tägliches Wachstum', reset: 'Zurücksetzen', download: 'Bericht herunterladen', summary: 'Kapazitätsübersicht', usable: 'Nutzbare Adressen', remaining: 'Adressen verbleiben', runway: 'Tage Reichweite', findings: 'Hinweise', assumptions: 'Annahmen und Grenzen', sources: 'Maßgebliche Quellen', invalid: 'Gib ein gültiges IPv4-CIDR ein.', none: 'Keine Kapazitäts- oder Kollisionshinweise.', bar: 'Adressraumauslastung' },
};

export function ScopeTool({ locale }: ToolPanelProps) {
  const [state, setState] = useState(defaults);
  const c = copy[locale];
  const cidr = useMemo(() => analyzeIpv4Cidr(state.cidr), [state.cidr]);
  const result = useMemo(() => analyzeScopeDesign({ scopes: [{ id: 'primary', cidr: state.cidr, gateway: state.gateway, pool: { start: state.poolStart, end: state.poolEnd }, exclusions: parseRanges(state.exclusions), reservations: lines(state.reservations).map((address, index) => ({ id: `reservation-${index}`, address })), leases: state.leases }], dailyGrowth: state.growth }), [state]);
  const capacity = result.scopes[0]!;
  const utilization = Math.min(100, Math.max(0, capacity.utilizationPercent));
  const update = (key: keyof typeof defaults, value: string | number) => setState((current) => ({ ...current, [key]: value }));
  const report = () => buildWorkbenchReport({ toolId: 'scope', toolName: locale === 'de' ? 'Bereich und Kapazität' : 'Scope and capacity', generatedAt: new Date().toISOString(), inputs: state, findings: result.findings.map((finding) => ({ severity: finding.severity, title: findingLabel(finding.key, locale), detail: `Scope ${finding.scopeId}` })), assumptions: [locale === 'de' ? 'Die Reichweite nimmt gleichmäßiges tägliches Wachstum an.' : 'Runway assumes steady daily growth.'], sources: [{ label: 'RFC 2131', url: 'https://www.rfc-editor.org/rfc/rfc2131.html' }, { label: 'RFC 4632', url: 'https://www.rfc-editor.org/rfc/rfc4632.html' }] });
  return <div className="workbench-grid" data-testid="tool-panel-scope">
    <section className="planner-card workbench-form" aria-labelledby="scope-form-title"><h2 id="scope-form-title">{c.title}</h2>
      <div className="workbench-fields"><Field label={c.cidr} value={state.cidr} onChange={(value) => update('cidr', value)} error={!cidr ? c.invalid : undefined} /><Field label={c.gateway} value={state.gateway} onChange={(value) => update('gateway', value)} /><Field label={c.start} value={state.poolStart} onChange={(value) => update('poolStart', value)} /><Field label={c.end} value={state.poolEnd} onChange={(value) => update('poolEnd', value)} /><TextField label={c.exclusions} value={state.exclusions} onChange={(value) => update('exclusions', value)} /><TextField label={c.reservations} value={state.reservations} onChange={(value) => update('reservations', value)} /><NumberField label={c.leases} value={state.leases} onChange={(value) => update('leases', value)} /><NumberField label={c.growth} value={state.growth} onChange={(value) => update('growth', value)} /></div>
      <div className="workbench-actions"><button className="secondary-button" type="button" onClick={() => setState(defaults)}>{c.reset}</button><button className="primary-button" type="button" onClick={() => downloadWorkbenchReport(report().markdown, 'dhcpulse-scope-report.md')}>{c.download}</button></div>
    </section>
    <section className="planner-card workbench-results" role="region" aria-labelledby="scope-results-title"><h2 id="scope-results-title">{c.summary}</h2>
      {cidr && <><div className="metric-grid workbench-metrics"><div className="metric"><span>{c.usable}</span><strong className="metric-value">{cidr.usableAddresses}</strong></div><div className="metric"><span>{c.remaining}</span><strong>{capacity.remainingAddresses}</strong></div><div className="metric"><span>{c.runway}</span><strong>{capacity.exhaustionDays === null ? '∞' : Math.floor(capacity.exhaustionDays)}</strong></div></div><dl className="fact-grid"><div><dt>Network</dt><dd>{cidr.network}</dd></div><div><dt>Broadcast</dt><dd>{cidr.broadcast}</dd></div><div><dt>Netmask</dt><dd>{cidr.netmask}</dd></div><div><dt>Wildcard</dt><dd>{cidr.wildcardMask}</dd></div><div><dt>Usable range</dt><dd>{cidr.firstUsable} - {cidr.lastUsable}</dd></div></dl><div className="address-bar" role="img" aria-label={`${c.bar}: ${Math.round(utilization)}%`}><span style={{ width: `${utilization}%` }} /></div><p>{capacity.remainingAddresses} {c.remaining}; {Math.round(capacity.utilizationPercent)}% used.</p></>}
      <FindingList title={c.findings} none={c.none} findings={result.findings.map((finding) => ({ severity: finding.severity, text: findingLabel(finding.key, locale) }))} /><Info title={c.assumptions} items={[locale === 'de' ? 'Die Reichweite nimmt gleichmäßiges tägliches Wachstum an; tatsächliche Lease-Verteilung kann abweichen.' : 'Runway assumes steady daily growth; actual lease distribution can vary.']} /><Sources title={c.sources} /></section>
  </div>;
}

function Field({ label, value, onChange, error }: { label: string; value: string; onChange: (value: string) => void; error?: string }) { const id = `scope-${label.replace(/\W/g, '-')}`; return <label className="workbench-field" htmlFor={id}><span>{label}</span><input id={id} value={value} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} onChange={(event) => onChange(event.target.value)} />{error && <small id={`${id}-error`} className="field-error">{error}</small>}</label>; }
function TextField(props: Omit<Parameters<typeof Field>[0], 'error'>) { const id = `scope-${props.label.replace(/\W/g, '-')}`; return <label className="workbench-field span-2" htmlFor={id}><span>{props.label}</span><textarea id={id} value={props.value} onChange={(event) => props.onChange(event.target.value)} /></label>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { const id = `scope-${label.replace(/\W/g, '-')}`; return <label className="workbench-field" htmlFor={id}><span>{label}</span><input id={id} type="number" min="0" value={value} onChange={(event) => onChange(event.target.valueAsNumber || 0)} /></label>; }
function lines(value: string) { return value.split(/\r?\n/).map((item) => item.trim()).filter(Boolean); }
function parseRanges(value: string) { return lines(value).flatMap((item) => { const match = /^\s*([^\s-]+)\s*-\s*([^\s-]+)\s*$/.exec(item); return match ? [{ start: match[1]!, end: match[2]! }] : []; }); }
function findingLabel(key: string, locale: 'en' | 'de') { const labels: Record<string, [string, string]> = { invalidCidr: ['Invalid CIDR', 'Ungültiges CIDR'], invalidPoolRange: ['Invalid pool range', 'Ungültiger Pool-Bereich'], poolOutsideSubnet: ['Pool is outside the subnet', 'Pool liegt außerhalb des Subnetzes'], invalidExclusionRange: ['Invalid exclusion range', 'Ungültiger Ausschlussbereich'], exclusionOutsidePool: ['Exclusion is outside the pool', 'Ausschluss liegt außerhalb des Pools'], reservationOutsideSubnet: ['Reservation is outside the subnet', 'Reservierung liegt außerhalb des Subnetzes'], duplicateReservationAddress: ['Duplicate reservation address', 'Doppelte Reservierungsadresse'], gatewayInDynamicPool: ['Gateway is inside the dynamic pool', 'Gateway liegt im dynamischen Pool'], overlappingScopeNetworks: ['Scope networks overlap', 'Scope-Netze überlappen'], overlappingDynamicPools: ['Dynamic pools overlap', 'Dynamische Pools überlappen'], overCapacityCurrentLeases: ['Current leases exceed capacity', 'Aktuelle Leases überschreiten die Kapazität'], exhaustionWithin30Days: ['Capacity may be exhausted within 30 days', 'Kapazität könnte innerhalb von 30 Tagen erschöpft sein'] }; return labels[key]?.[locale === 'de' ? 1 : 0] ?? key; }
function FindingList({ title, findings, none }: { title: string; findings: { severity: string; text: string }[]; none: string }) { return <section className="workbench-section"><h3>{title}</h3>{findings.length ? <ul className="finding-list-compact">{findings.map((finding, index) => <li key={`${finding.text}-${index}`} className={`finding-${finding.severity}`}><span className="severity">{finding.severity}</span>{finding.text}</li>)}</ul> : <p>{none}</p>}</section>; }
function Info({ title, items }: { title: string; items: string[] }) { return <details className="workbench-section"><summary>{title}</summary><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></details>; }
function Sources({ title }: { title: string }) { return <section className="workbench-section"><h3>{title}</h3><ul><li><a href="https://www.rfc-editor.org/rfc/rfc2131.html" target="_blank" rel="noreferrer">RFC 2131</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc4632.html" target="_blank" rel="noreferrer">RFC 4632</a></li></ul></section>; }
