import { useMemo, useState } from 'react';
import { securityRuleCatalog } from '../content/diagnostic-rules';
import { diagnoseDhcp } from '../domain/diagnostics';
import type { DhcpDiagnosticInput, DhcpSecurityEvidence, DhcpSecurityFindingId } from '../domain/types';
import { buildWorkbenchReport, downloadWorkbenchReport } from '../domain/workbench-export';
import type { ToolPanelProps } from './ToolPanel';

const defaults:DhcpSecurityEvidence={dhcpSnoopingEnabled:false,serverFacingPortsTrusted:false,option82Trusted:false,dnsUpdateCredentialsAligned:false,auditLoggingEnabled:false,windowsDhcpAuthorized:false,raGuardEnabled:false,backupRestoreTested:false,secretExposureDetected:false};
const base:Omit<DhcpDiagnosticInput,'security'>={symptoms:[],path:'direct',affectedVlans:'all',existingClientsAffected:false,newClientsAffected:false,serverPlatform:'windows',recentChange:false,offerSeen:false,requestSeen:false,ackSeen:false,nakSeen:false,declineSeen:false,relayGiaddr:null,relayLinkAddress:null,serverIds:[],freePoolPercentage:50,dnsQueueSymptoms:false,failoverState:'normal'};
const copy={en:{title:'Defensive DHCP controls',description:'Select controls that are implemented and verified. Gaps remain explainable and grouped by defensive purpose.',reset:'Reset',download:'Download report',gaps:'Configuration gaps',prevent:'Prevent',detect:'Detect',recover:'Recover',none:'No gap in this group.',assumptions:'Assumptions and limitations',sources:'Authoritative sources'},de:{title:'Defensive DHCP-Schutzmaßnahmen',description:'Wähle implementierte und geprüfte Maßnahmen. Lücken bleiben nachvollziehbar und sind nach Schutzzweck gruppiert.',reset:'Zurücksetzen',download:'Bericht herunterladen',gaps:'Konfigurationslücken',prevent:'Verhindern',detect:'Erkennen',recover:'Wiederherstellen',none:'Keine Lücke in dieser Gruppe.',assumptions:'Annahmen und Grenzen',sources:'Maßgebliche Quellen'}};
const controls: [keyof DhcpSecurityEvidence,string,string][]=[['dhcpSnoopingEnabled','DHCP snooping enabled','DHCP Snooping aktiviert'],['serverFacingPortsTrusted','Only server/relay-facing ports trusted','Nur Server-/Relay-Ports vertrauenswürdig'],['option82Trusted','Option 82 trust boundary defined','Option-82-Vertrauensgrenze definiert'],['raGuardEnabled','RA Guard enabled','RA Guard aktiviert'],['windowsDhcpAuthorized','Windows DHCP authorized','Windows DHCP autorisiert'],['auditLoggingEnabled','DHCP audit logging enabled','DHCP-Auditprotokollierung aktiviert'],['dnsUpdateCredentialsAligned','DNS update credentials aligned','DNS-Update-Anmeldedaten abgestimmt'],['backupRestoreTested','Backup restore tested','Wiederherstellung getestet'],['secretExposureDetected','API/config secret exposure detected','API-/Konfigurationssecret offengelegt']];
const groups:Record<'prevent'|'detect'|'recover',DhcpSecurityFindingId[]>={prevent:['security-dhcp-snooping-disabled','security-trusted-port-misconfigured','security-option-82-trust-missing','security-windows-dhcp-unauthorized','security-ra-guard-disabled','security-secret-exposure'],detect:['security-rogue-dhcp-server','security-starvation-or-exhaustion','security-audit-logging-disabled','security-dns-credential-mismatch'],recover:['security-backup-restore-unverified']};

export function SecurityTool({locale}:ToolPanelProps){const [state,setState]=useState(defaults);const c=copy[locale];const result=useMemo(()=>diagnoseDhcp({...base,security:state}),[state]);const download=()=>{const report=buildWorkbenchReport({toolId:'security',toolName:locale==='de'?'DHCP-Sicherheit':'DHCP security',generatedAt:new Date().toISOString(),inputs:Object.fromEntries(controls.map(([key])=>[key,state[key]])),findings:result.securityFindings.map(f=>({severity:f.severity,title:securityRuleCatalog[f.id].title,detail:f.rationale})),assumptions:[locale==='de'?'Die Checkliste bestätigt keine technische Umsetzung; Nachweise sind separat zu prüfen.':'The checklist does not prove implementation; validate evidence separately.'],sources:[...new Map(result.securityFindings.map(f=>[f.source,{label:securityRuleCatalog[f.id].title,url:f.source}])).values()]});downloadWorkbenchReport(report.markdown,'dhcpulse-security-report.md');};return <div className="workbench-grid" data-testid="tool-panel-security"><section className="planner-card workbench-form" aria-labelledby="security-title"><h2 id="security-title">{c.title}</h2><p>{c.description}</p><div className="security-checklist">{controls.map(([key,en,de])=><label className="check-row" key={key}><input type="checkbox" checked={state[key]} onChange={e=>setState(current=>({...current,[key]:e.target.checked}))}/>{locale==='de'?de:en}</label>)}</div><div className="workbench-actions"><button type="button" className="secondary-button" onClick={()=>setState(defaults)}>{c.reset}</button><button type="button" className="primary-button" onClick={download}>{c.download}</button></div></section><section className="planner-card workbench-results" role="region" aria-labelledby="security-result"><h2 id="security-result">{c.gaps}</h2>{(Object.keys(groups) as (keyof typeof groups)[]).map(group=><section className="workbench-section" key={group}><h3>{c[group]}</h3>{findings(group,result.securityFindings).length?<ul className="finding-list-compact">{findings(group,result.securityFindings).map(f=><li key={f.id} className={`finding-${f.severity}`}><span className="severity">{f.severity}</span><div><strong>{securityRuleCatalog[f.id].title}</strong><p>{f.rationale}</p><a href={f.source} target="_blank" rel="noreferrer">Source</a></div></li>)}</ul>:<p>{c.none}</p>}</section>)}<details className="workbench-section"><summary>{c.assumptions}</summary><p>{locale==='de'?'Bewertung basiert ausschließlich auf den ausgewählten Kontrollnachweisen.':'Assessment uses only the selected control evidence.'}</p></details><section className="workbench-section"><h3>{c.sources}</h3><a href="https://www.rfc-editor.org/rfc/rfc3046.html" target="_blank" rel="noreferrer">RFC 3046</a> · <a href="https://www.rfc-editor.org/rfc/rfc7113.html" target="_blank" rel="noreferrer">RFC 7113</a></section></section></div>}
function findings(group:keyof typeof groups,values:ReturnType<typeof diagnoseDhcp>['securityFindings']){return values.filter(value=>groups[group].includes(value.id));}
